/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.DirectUploadVideoMediaRequest;
import org.openapis.openapi.operations.DirectUploadVideoMedia;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class DirectUploadVideoMediaRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private DirectUploadVideoMediaRequest request;
    private final Options.Builder optionsBuilder;

    public DirectUploadVideoMediaRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public DirectUploadVideoMediaRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public DirectUploadVideoMediaRequestBuilder request(@Nullable DirectUploadVideoMediaRequest request) {
        this.request = request;
        return this;
    }

    private DirectUploadVideoMediaRequest _buildRequest() {
        return this.request;
    }
    
    public DirectUploadVideoMediaRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<DirectUploadVideoMediaResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<DirectUploadVideoMediaRequest, DirectUploadVideoMediaResponse> operation
              = new DirectUploadVideoMedia.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
