/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.SortOrder;
import org.openapis.openapi.models.operations.ListLiveClipsRequest;
import org.openapis.openapi.operations.ListLiveClips;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class ListLiveClipsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final ListLiveClipsRequest.Builder pojoBuilder;
    private ListLiveClipsRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public ListLiveClipsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ListLiveClipsRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public ListLiveClipsRequestBuilder livestreamId(@Nonnull String livestreamId) {
        this.pojoBuilder.livestreamId(livestreamId);
        this._setterCalled = true;
        return this;
    }

    public ListLiveClipsRequestBuilder limit(@Nullable Long limit) {
        this.pojoBuilder.limit(limit);
        this._setterCalled = true;
        return this;
    }

    public ListLiveClipsRequestBuilder offset(@Nullable Long offset) {
        this.pojoBuilder.offset(offset);
        this._setterCalled = true;
        return this;
    }

    public ListLiveClipsRequestBuilder orderBy(@Nullable SortOrder orderBy) {
        this.pojoBuilder.orderBy(orderBy);
        this._setterCalled = true;
        return this;
    }

    public ListLiveClipsRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private ListLiveClipsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public ListLiveClipsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<ListLiveClipsResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<ListLiveClipsRequest, ListLiveClipsResponse> operation
              = new ListLiveClips.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
