/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package io.fastpix.sdk.models.operations.async;

import static io.fastpix.sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import io.fastpix.sdk.SDKConfiguration;
import io.fastpix.sdk.models.operations.DeleteSimulcastOfStreamRequest;
import io.fastpix.sdk.operations.DeleteSimulcastOfStream;
import io.fastpix.sdk.utils.Headers;
import io.fastpix.sdk.utils.Options;
import io.fastpix.sdk.utils.RetryConfig;
import io.fastpix.sdk.utils.Utils;

public class DeleteSimulcastOfStreamRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final DeleteSimulcastOfStreamRequest.Builder pojoBuilder;
    private DeleteSimulcastOfStreamRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public DeleteSimulcastOfStreamRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DeleteSimulcastOfStreamRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public DeleteSimulcastOfStreamRequestBuilder streamId(@Nonnull String streamId) {
        this.pojoBuilder.streamId(streamId);
        this._setterCalled = true;
        return this;
    }

    public DeleteSimulcastOfStreamRequestBuilder simulcastId(@Nonnull String simulcastId) {
        this.pojoBuilder.simulcastId(simulcastId);
        this._setterCalled = true;
        return this;
    }

    public DeleteSimulcastOfStreamRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private DeleteSimulcastOfStreamRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public DeleteSimulcastOfStreamRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<DeleteSimulcastOfStreamResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<DeleteSimulcastOfStreamRequest, DeleteSimulcastOfStreamResponse> operation
              = new DeleteSimulcastOfStream.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
