/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package io.fastpix.sdk.models.operations.async;

import static io.fastpix.sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import io.fastpix.sdk.SDKConfiguration;
import io.fastpix.sdk.models.operations.ListOverallValuesMetricId;
import io.fastpix.sdk.models.operations.ListOverallValuesRequest;
import io.fastpix.sdk.models.operations.ListOverallValuesTimespan;
import io.fastpix.sdk.operations.ListOverallValues;
import io.fastpix.sdk.utils.Headers;
import io.fastpix.sdk.utils.Options;
import io.fastpix.sdk.utils.RetryConfig;
import io.fastpix.sdk.utils.Utils;

public class ListOverallValuesRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final ListOverallValuesRequest.Builder pojoBuilder;
    private ListOverallValuesRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public ListOverallValuesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ListOverallValuesRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public ListOverallValuesRequestBuilder metricId(@Nonnull ListOverallValuesMetricId metricId) {
        this.pojoBuilder.metricId(metricId);
        this._setterCalled = true;
        return this;
    }

    public ListOverallValuesRequestBuilder measurement(@Nullable String measurement) {
        this.pojoBuilder.measurement(measurement);
        this._setterCalled = true;
        return this;
    }

    public ListOverallValuesRequestBuilder timespan(@Nullable ListOverallValuesTimespan timespan) {
        this.pojoBuilder.timespan(timespan);
        this._setterCalled = true;
        return this;
    }

    public ListOverallValuesRequestBuilder filterby(@Nullable String filterby) {
        this.pojoBuilder.filterby(filterby);
        this._setterCalled = true;
        return this;
    }

    public ListOverallValuesRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private ListOverallValuesRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public ListOverallValuesRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<ListOverallValuesResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<ListOverallValuesRequest, ListOverallValuesResponse> operation
              = new ListOverallValues.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
