/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.DomainRestrictions;
import org.openapis.openapi.models.components.UserAgentRestrictions;
import org.openapis.openapi.utils.Utils;


public class CreateMediaPlaybackIdAccessRestrictions {
    /**
     * Restrictions based on the originating domain of a request
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("domains")
    private DomainRestrictions domains;

    /**
     * Restrictions based on the user agent
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userAgents")
    private UserAgentRestrictions userAgents;

    @JsonCreator
    public CreateMediaPlaybackIdAccessRestrictions(
            @JsonProperty("domains") @Nullable DomainRestrictions domains,
            @JsonProperty("userAgents") @Nullable UserAgentRestrictions userAgents) {
        this.domains = domains;
        this.userAgents = userAgents;
    }
    
    public CreateMediaPlaybackIdAccessRestrictions() {
        this(null, null);
    }

    /**
     * Restrictions based on the originating domain of a request
     */
    public Optional<DomainRestrictions> domains() {
        return Optional.ofNullable(this.domains);
    }

    /**
     * Restrictions based on the user agent
     */
    public Optional<UserAgentRestrictions> userAgents() {
        return Optional.ofNullable(this.userAgents);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Restrictions based on the originating domain of a request
     */
    public CreateMediaPlaybackIdAccessRestrictions withDomains(@Nullable DomainRestrictions domains) {
        this.domains = domains;
        return this;
    }


    /**
     * Restrictions based on the user agent
     */
    public CreateMediaPlaybackIdAccessRestrictions withUserAgents(@Nullable UserAgentRestrictions userAgents) {
        this.userAgents = userAgents;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateMediaPlaybackIdAccessRestrictions other = (CreateMediaPlaybackIdAccessRestrictions) o;
        return 
            Utils.enhancedDeepEquals(this.domains, other.domains) &&
            Utils.enhancedDeepEquals(this.userAgents, other.userAgents);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            domains, userAgents);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateMediaPlaybackIdAccessRestrictions.class,
                "domains", domains,
                "userAgents", userAgents);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private DomainRestrictions domains;

        private UserAgentRestrictions userAgents;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Restrictions based on the originating domain of a request
         */
        public Builder domains(@Nullable DomainRestrictions domains) {
            this.domains = domains;
            return this;
        }

        /**
         * Restrictions based on the user agent
         */
        public Builder userAgents(@Nullable UserAgentRestrictions userAgents) {
            this.userAgents = userAgents;
            return this;
        }

        public CreateMediaPlaybackIdAccessRestrictions build() {
            return new CreateMediaPlaybackIdAccessRestrictions(
                domains, userAgents);
        }

    }
}
