/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.FastpixMetadata;
import org.openapis.openapi.utils.Utils;


public class GetAllPlaylistsRequest {
    /**
     * The number of playlists to return (default is 10, max is 50).
     */
    @FastpixMetadata("queryParam:style=form,explode=true,name=limit")
    private Long limit;

    /**
     * The page number to retrieve, starting from 1. Use this parameter to paginate the playlist results.
     */
    @FastpixMetadata("queryParam:style=form,explode=true,name=offset")
    private Long offset;

    @JsonCreator
    public GetAllPlaylistsRequest(
            @Nullable Long limit,
            @Nullable Long offset) {
        this.limit = Optional.ofNullable(limit)
            .orElse(Builder._SINGLETON_VALUE_Limit.value());
        this.offset = Optional.ofNullable(offset)
            .orElse(Builder._SINGLETON_VALUE_Offset.value());
    }
    
    public GetAllPlaylistsRequest() {
        this(null, null);
    }

    /**
     * The number of playlists to return (default is 10, max is 50).
     */
    public Optional<Long> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * The page number to retrieve, starting from 1. Use this parameter to paginate the playlist results.
     */
    public Optional<Long> offset() {
        return Optional.ofNullable(this.offset);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The number of playlists to return (default is 10, max is 50).
     */
    public GetAllPlaylistsRequest withLimit(@Nullable Long limit) {
        this.limit = limit;
        return this;
    }


    /**
     * The page number to retrieve, starting from 1. Use this parameter to paginate the playlist results.
     */
    public GetAllPlaylistsRequest withOffset(@Nullable Long offset) {
        this.offset = offset;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAllPlaylistsRequest other = (GetAllPlaylistsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.limit, other.limit) &&
            Utils.enhancedDeepEquals(this.offset, other.offset);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            limit, offset);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAllPlaylistsRequest.class,
                "limit", limit,
                "offset", offset);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Long limit;

        private Long offset;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The number of playlists to return (default is 10, max is 50).
         */
        public Builder limit(@Nullable Long limit) {
            this.limit = limit;
            return this;
        }

        /**
         * The page number to retrieve, starting from 1. Use this parameter to paginate the playlist results.
         */
        public Builder offset(@Nullable Long offset) {
            this.offset = offset;
            return this;
        }

        public GetAllPlaylistsRequest build() {
            return new GetAllPlaylistsRequest(
                limit, offset);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Limit =
                new LazySingletonValue<>(
                        "limit",
                        "10",
                        new TypeReference<Long>() {});

        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Offset =
                new LazySingletonValue<>(
                        "offset",
                        "1",
                        new TypeReference<Long>() {});
    }
}
