/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Long;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetAllStreams;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class GetAllStreamsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetAllStreamsRequest.Builder pojoBuilder;
    private GetAllStreamsRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public GetAllStreamsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetAllStreamsRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public GetAllStreamsRequestBuilder limit(@Nullable Long limit) {
        this.pojoBuilder.limit(limit);
        this._setterCalled = true;
        return this;
    }

    public GetAllStreamsRequestBuilder offset(@Nullable Long offset) {
        this.pojoBuilder.offset(offset);
        this._setterCalled = true;
        return this;
    }

    public GetAllStreamsRequestBuilder orderBy(@Nullable OrderBy orderBy) {
        this.pojoBuilder.orderBy(orderBy);
        this._setterCalled = true;
        return this;
    }

    public GetAllStreamsRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private GetAllStreamsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetAllStreamsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetAllStreamsResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<GetAllStreamsRequest, GetAllStreamsResponse> operation
              = new GetAllStreams.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
