/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.FastpixMetadata;
import org.openapis.openapi.utils.Utils;


public class GetVideoViewDetailsRequest {
    /**
     * Pass View Id
     */
    @FastpixMetadata("pathParam:style=simple,explode=false,name=viewId")
    private String viewId;

    @JsonCreator
    public GetVideoViewDetailsRequest(
            @Nonnull String viewId) {
        this.viewId = Optional.ofNullable(viewId)
            .orElseThrow(() -> new IllegalArgumentException("viewId cannot be null"));
    }

    /**
     * Pass View Id
     */
    public String viewId() {
        return this.viewId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Pass View Id
     */
    public GetVideoViewDetailsRequest withViewId(@Nonnull String viewId) {
        this.viewId = Utils.checkNotNull(viewId, "viewId");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetVideoViewDetailsRequest other = (GetVideoViewDetailsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.viewId, other.viewId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            viewId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetVideoViewDetailsRequest.class,
                "viewId", viewId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String viewId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Pass View Id
         */
        public Builder viewId(@Nonnull String viewId) {
            this.viewId = Utils.checkNotNull(viewId, "viewId");
            return this;
        }

        public GetVideoViewDetailsRequest build() {
            return new GetVideoViewDetailsRequest(
                viewId);
        }

    }
}
