/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.ListFilterValuesForDimension;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.Utils;

public class ListFilterValuesForDimensionRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final ListFilterValuesForDimensionRequest.Builder pojoBuilder;
    private ListFilterValuesForDimensionRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public ListFilterValuesForDimensionRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ListFilterValuesForDimensionRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public ListFilterValuesForDimensionRequestBuilder dimensionsId(@Nonnull DimensionsId dimensionsId) {
        this.pojoBuilder.dimensionsId(dimensionsId);
        this._setterCalled = true;
        return this;
    }

    public ListFilterValuesForDimensionRequestBuilder timespan(@Nullable ListFilterValuesForDimensionTimespan timespan) {
        this.pojoBuilder.timespan(timespan);
        this._setterCalled = true;
        return this;
    }

    public ListFilterValuesForDimensionRequestBuilder filterby(@Nullable String filterby) {
        this.pojoBuilder.filterby(filterby);
        this._setterCalled = true;
        return this;
    }

    public ListFilterValuesForDimensionRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private ListFilterValuesForDimensionRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public ListFilterValuesForDimensionRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ListFilterValuesForDimensionResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<ListFilterValuesForDimensionRequest, ListFilterValuesForDimensionResponse> operation
              = new ListFilterValuesForDimension.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
