/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;
import org.openapis.openapi.models.components.DefaultError;
import org.openapis.openapi.models.components.GetAllSigningKeysResponse;
import org.openapis.openapi.utils.Response;
import org.openapis.openapi.utils.Utils;


public class ListSigningKeysResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * successfully fetched all signing keys
     */
    private GetAllSigningKeysResponse getAllSigningKeysResponse;

    /**
     * See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a>
     * responses and their status codes.
     */
    private DefaultError defaultError;

    @JsonCreator
    public ListSigningKeysResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse,
            @Nullable GetAllSigningKeysResponse getAllSigningKeysResponse,
            @Nullable DefaultError defaultError) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.getAllSigningKeysResponse = getAllSigningKeysResponse;
        this.defaultError = defaultError;
    }
    
    public ListSigningKeysResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null, null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    /**
     * successfully fetched all signing keys
     */
    public Optional<GetAllSigningKeysResponse> getAllSigningKeysResponse() {
        return Optional.ofNullable(this.getAllSigningKeysResponse);
    }

    /**
     * See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a>
     * responses and their status codes.
     */
    public Optional<DefaultError> defaultError() {
        return Optional.ofNullable(this.defaultError);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListSigningKeysResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public ListSigningKeysResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListSigningKeysResponse withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * successfully fetched all signing keys
     */
    public ListSigningKeysResponse withGetAllSigningKeysResponse(@Nullable GetAllSigningKeysResponse getAllSigningKeysResponse) {
        this.getAllSigningKeysResponse = getAllSigningKeysResponse;
        return this;
    }


    /**
     * See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a>
     * responses and their status codes.
     */
    public ListSigningKeysResponse withDefaultError(@Nullable DefaultError defaultError) {
        this.defaultError = defaultError;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListSigningKeysResponse other = (ListSigningKeysResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.getAllSigningKeysResponse, other.getAllSigningKeysResponse) &&
            Utils.enhancedDeepEquals(this.defaultError, other.defaultError);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            getAllSigningKeysResponse, defaultError);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListSigningKeysResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "getAllSigningKeysResponse", getAllSigningKeysResponse,
                "defaultError", defaultError);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private GetAllSigningKeysResponse getAllSigningKeysResponse;

        private DefaultError defaultError;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * successfully fetched all signing keys
         */
        public Builder getAllSigningKeysResponse(@Nullable GetAllSigningKeysResponse getAllSigningKeysResponse) {
            this.getAllSigningKeysResponse = getAllSigningKeysResponse;
            return this;
        }

        /**
         * See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a>
         * responses and their status codes.
         */
        public Builder defaultError(@Nullable DefaultError defaultError) {
            this.defaultError = defaultError;
            return this;
        }

        public ListSigningKeysResponse build() {
            return new ListSigningKeysResponse(
                contentType, statusCode, rawResponse,
                getAllSigningKeysResponse, defaultError);
        }

    }
}
