/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class ListPlaybackIdsDomainsDefaultPolicy {

    public static final ListPlaybackIdsDomainsDefaultPolicy ALLOW = new ListPlaybackIdsDomainsDefaultPolicy("allow");
    public static final ListPlaybackIdsDomainsDefaultPolicy DENY = new ListPlaybackIdsDomainsDefaultPolicy("deny");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ListPlaybackIdsDomainsDefaultPolicy> values = createValuesMap();
    private static final Map<String, ListPlaybackIdsDomainsDefaultPolicyEnum> enums = createEnumsMap();

    private final String value;

    private ListPlaybackIdsDomainsDefaultPolicy(String value) {
        this.value = value;
    }

    /**
     * Returns a ListPlaybackIdsDomainsDefaultPolicy with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ListPlaybackIdsDomainsDefaultPolicy
     */ 
    @JsonCreator
    public static ListPlaybackIdsDomainsDefaultPolicy of(String value) {
        synchronized (ListPlaybackIdsDomainsDefaultPolicy.class) {
            return values.computeIfAbsent(value, v -> new ListPlaybackIdsDomainsDefaultPolicy(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ListPlaybackIdsDomainsDefaultPolicyEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ListPlaybackIdsDomainsDefaultPolicy other = (ListPlaybackIdsDomainsDefaultPolicy) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ListPlaybackIdsDomainsDefaultPolicy [value=" + value + "]";
    }

    // return an array just like an enum
    public static ListPlaybackIdsDomainsDefaultPolicy[] values() {
        synchronized (ListPlaybackIdsDomainsDefaultPolicy.class) {
            return values.values().toArray(new ListPlaybackIdsDomainsDefaultPolicy[] {});
        }
    }

    private static final Map<String, ListPlaybackIdsDomainsDefaultPolicy> createValuesMap() {
        Map<String, ListPlaybackIdsDomainsDefaultPolicy> map = new LinkedHashMap<>();
        map.put("allow", ALLOW);
        map.put("deny", DENY);
        return map;
    }

    private static final Map<String, ListPlaybackIdsDomainsDefaultPolicyEnum> createEnumsMap() {
        Map<String, ListPlaybackIdsDomainsDefaultPolicyEnum> map = new HashMap<>();
        map.put("allow", ListPlaybackIdsDomainsDefaultPolicyEnum.ALLOW);
        map.put("deny", ListPlaybackIdsDomainsDefaultPolicyEnum.DENY);
        return map;
    }
    
    
    public enum ListPlaybackIdsDomainsDefaultPolicyEnum {

        ALLOW("allow"),
        DENY("deny"),;

        private final String value;

        private ListPlaybackIdsDomainsDefaultPolicyEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

