/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.models.components.MetricsComparisonDetails;
import org.openapis.openapi.utils.Utils;

/**
 * ListComparisonValuesResponseBody
 * 
 * <p>Get filter/ dimension value details by dimension name.
 */
public class ListComparisonValuesResponseBody {
    /**
     * Shows the request status. Returns true for success and false for failure.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("success")
    private Boolean success;

    /**
     * Displays the result of the request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private List<MetricsComparisonDetails> data;

    /**
     * The timespan from and to details displayed in the form of unix epoch timestamps.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timespan")
    private List<Long> timespan;

    @JsonCreator
    public ListComparisonValuesResponseBody(
            @JsonProperty("success") @Nullable Boolean success,
            @JsonProperty("data") @Nullable List<MetricsComparisonDetails> data,
            @JsonProperty("timespan") @Nullable List<Long> timespan) {
        this.success = success;
        this.data = data;
        this.timespan = timespan;
    }
    
    public ListComparisonValuesResponseBody() {
        this(null, null, null);
    }

    /**
     * Shows the request status. Returns true for success and false for failure.
     */
    public Optional<Boolean> success() {
        return Optional.ofNullable(this.success);
    }

    /**
     * Displays the result of the request.
     */
    public Optional<List<MetricsComparisonDetails>> data() {
        return Optional.ofNullable(this.data);
    }

    /**
     * The timespan from and to details displayed in the form of unix epoch timestamps.
     */
    public Optional<List<Long>> timespan() {
        return Optional.ofNullable(this.timespan);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Shows the request status. Returns true for success and false for failure.
     */
    public ListComparisonValuesResponseBody withSuccess(@Nullable Boolean success) {
        this.success = success;
        return this;
    }


    /**
     * Displays the result of the request.
     */
    public ListComparisonValuesResponseBody withData(@Nullable List<MetricsComparisonDetails> data) {
        this.data = data;
        return this;
    }


    /**
     * The timespan from and to details displayed in the form of unix epoch timestamps.
     */
    public ListComparisonValuesResponseBody withTimespan(@Nullable List<Long> timespan) {
        this.timespan = timespan;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListComparisonValuesResponseBody other = (ListComparisonValuesResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.success, other.success) &&
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.timespan, other.timespan);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            success, data, timespan);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListComparisonValuesResponseBody.class,
                "success", success,
                "data", data,
                "timespan", timespan);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Boolean success;

        private List<MetricsComparisonDetails> data;

        private List<Long> timespan;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Shows the request status. Returns true for success and false for failure.
         */
        public Builder success(@Nullable Boolean success) {
            this.success = success;
            return this;
        }

        /**
         * Displays the result of the request.
         */
        public Builder data(@Nullable List<MetricsComparisonDetails> data) {
            this.data = data;
            return this;
        }

        /**
         * The timespan from and to details displayed in the form of unix epoch timestamps.
         */
        public Builder timespan(@Nullable List<Long> timespan) {
            this.timespan = timespan;
            return this;
        }

        public ListComparisonValuesResponseBody build() {
            return new ListComparisonValuesResponseBody(
                success, data, timespan);
        }

    }
}
