/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import org.openapis.openapi.models.components.AudioTrack;
import org.openapis.openapi.models.components.SubtitleTrack;
import org.openapis.openapi.models.components.VideoTrack;
import org.openapis.openapi.utils.OneOfDeserializer;
import org.openapis.openapi.utils.TypedObject;
import org.openapis.openapi.utils.Utils.JsonShape;
import org.openapis.openapi.utils.Utils.TypeReferenceWithShape;
import org.openapis.openapi.utils.Utils;

@JsonDeserialize(using = Track._Deserializer.class)
public class Track {

    @JsonValue
    private final TypedObject value;
    
    private Track(TypedObject value) {
        this.value = value;
    }

    public static Track of(VideoTrack value) {
        Utils.checkNotNull(value, "value");
        return new Track(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static Track of(AudioTrack value) {
        Utils.checkNotNull(value, "value");
        return new Track(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static Track of(SubtitleTrack value) {
        Utils.checkNotNull(value, "value");
        return new Track(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code VideoTrack},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code VideoTrack} value, or empty if not of this type
     */
    public Optional<VideoTrack> videoTrack() {
        if (value.value() instanceof VideoTrack) {
            return Optional.of((VideoTrack) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code AudioTrack},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code AudioTrack} value, or empty if not of this type
     */
    public Optional<AudioTrack> audioTrack() {
        if (value.value() instanceof AudioTrack) {
            return Optional.of((AudioTrack) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code SubtitleTrack},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code SubtitleTrack} value, or empty if not of this type
     */
    public Optional<SubtitleTrack> subtitleTrack() {
        if (value.value() instanceof SubtitleTrack) {
            return Optional.of((SubtitleTrack) value.value());
        }
        return Optional.empty();
    }
   /**
    * Returns an {@link Optional} containing the value as a {@code JsonNode}.
    * This accessor returns the raw JSON when the value doesn't match any of the defined union types.
    *
    * @return an {@link Optional} containing the {@code JsonNode} value, or empty if value matched a known type
    */
   public Optional<JsonNode> asJson() {
       if (value.value() instanceof JsonNode) {
           return Optional.of((JsonNode) value.value());
       }
       return Optional.empty();
   }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Track other = (Track) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<Track> {

        public _Deserializer() {
            super(Track.class, false,
                  TypeReferenceWithShape.of(new TypeReference<VideoTrack>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<AudioTrack>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<SubtitleTrack>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(Track.class,
                "value", value);
    }

}

