/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.UpdateMedia;
import org.openapis.openapi.utils.Utils;

/**
 * UpdatedMediaResponseBody
 * 
 * <p>Media details updated successfully
 */
public class UpdatedMediaResponseBody {
    /**
     * Demonstrates whether the request is successful or not.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("success")
    private Boolean success;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private UpdateMedia data;

    @JsonCreator
    public UpdatedMediaResponseBody(
            @JsonProperty("success") @Nullable Boolean success,
            @JsonProperty("data") @Nullable UpdateMedia data) {
        this.success = success;
        this.data = data;
    }
    
    public UpdatedMediaResponseBody() {
        this(null, null);
    }

    /**
     * Demonstrates whether the request is successful or not.
     */
    public Optional<Boolean> success() {
        return Optional.ofNullable(this.success);
    }

    public Optional<UpdateMedia> data() {
        return Optional.ofNullable(this.data);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Demonstrates whether the request is successful or not.
     */
    public UpdatedMediaResponseBody withSuccess(@Nullable Boolean success) {
        this.success = success;
        return this;
    }


    public UpdatedMediaResponseBody withData(@Nullable UpdateMedia data) {
        this.data = data;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdatedMediaResponseBody other = (UpdatedMediaResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.success, other.success) &&
            Utils.enhancedDeepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            success, data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdatedMediaResponseBody.class,
                "success", success,
                "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Boolean success;

        private UpdateMedia data;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Demonstrates whether the request is successful or not.
         */
        public Builder success(@Nullable Boolean success) {
            this.success = success;
            return this;
        }

        public Builder data(@Nullable UpdateMedia data) {
            this.data = data;
            return this;
        }

        public UpdatedMediaResponseBody build() {
            return new UpdatedMediaResponseBody(
                success, data);
        }

    }
}
