/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;


public class UpdateMediaSummaryRequestBody {
    /**
     * Enable or disable the summary feature for the media. Set to true to enable summary or false to
     * disable.
     */
    @JsonProperty("generate")
    private boolean generate;

    /**
     * Specifies the desired word count for the generated summary.
     * - The value must be between **30** and **250** words.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("summaryLength")
    private Long summaryLength;

    @JsonCreator
    public UpdateMediaSummaryRequestBody(
            @JsonProperty("generate") boolean generate,
            @JsonProperty("summaryLength") @Nullable Long summaryLength) {
        this.generate = generate;
        this.summaryLength = Optional.ofNullable(summaryLength)
            .orElse(Builder._SINGLETON_VALUE_SummaryLength.value());
    }
    
    public UpdateMediaSummaryRequestBody(
            boolean generate) {
        this(generate, null);
    }

    /**
     * Enable or disable the summary feature for the media. Set to true to enable summary or false to
     * disable.
     */
    public boolean generate() {
        return this.generate;
    }

    /**
     * Specifies the desired word count for the generated summary.
     * - The value must be between **30** and **250** words.
     */
    public Optional<Long> summaryLength() {
        return Optional.ofNullable(this.summaryLength);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Enable or disable the summary feature for the media. Set to true to enable summary or false to
     * disable.
     */
    public UpdateMediaSummaryRequestBody withGenerate(boolean generate) {
        this.generate = generate;
        return this;
    }


    /**
     * Specifies the desired word count for the generated summary.
     * - The value must be between **30** and **250** words.
     */
    public UpdateMediaSummaryRequestBody withSummaryLength(@Nullable Long summaryLength) {
        this.summaryLength = summaryLength;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateMediaSummaryRequestBody other = (UpdateMediaSummaryRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.generate, other.generate) &&
            Utils.enhancedDeepEquals(this.summaryLength, other.summaryLength);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            generate, summaryLength);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateMediaSummaryRequestBody.class,
                "generate", generate,
                "summaryLength", summaryLength);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private boolean generate;

        private Long summaryLength;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Enable or disable the summary feature for the media. Set to true to enable summary or false to
         * disable.
         */
        public Builder generate(boolean generate) {
            this.generate = generate;
            return this;
        }

        /**
         * Specifies the desired word count for the generated summary.
         * - The value must be between **30** and **250** words.
         */
        public Builder summaryLength(@Nullable Long summaryLength) {
            this.summaryLength = summaryLength;
            return this;
        }

        public UpdateMediaSummaryRequestBody build() {
            return new UpdateMediaSummaryRequestBody(
                generate, summaryLength);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_SummaryLength =
                new LazySingletonValue<>(
                        "summaryLength",
                        "100",
                        new TypeReference<Long>() {});
    }
}
