/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateMediaRequestUserAgentsDefaultPolicy
 * 
 * <p>Specifies the default access policy for user agents (browsers, bots, etc.).
 * If set to `allow`, all user agents are allowed access unless otherwise specified in the `deny` lists. 
 * If set to `deny`, all user agents are denied access unless otherwise specified in the `allow` lists.
 */
public enum CreateMediaRequestUserAgentsDefaultPolicy {
    ALLOW("allow"),
    DENY("deny");

    @JsonValue
    private final String value;

    private CreateMediaRequestUserAgentsDefaultPolicy(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateMediaRequestUserAgentsDefaultPolicy> fromValue(String value) {
        for (CreateMediaRequestUserAgentsDefaultPolicy o: CreateMediaRequestUserAgentsDefaultPolicy.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

