/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateMediaRequestLanguageCode
 * 
 * <p>Language codes are concise, standardized symbols that denote languages, utilizing either two or three characters for identification. The language code must be compliant with the BCP 47 standard to ensure compatibility. (for text only).
 */
public enum CreateMediaRequestLanguageCode {
    EN("en"),
    IT("it"),
    PL("pl"),
    ES("es"),
    FR("fr"),
    RU("ru"),
    NL("nl");

    @JsonValue
    private final String value;

    private CreateMediaRequestLanguageCode(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateMediaRequestLanguageCode> fromValue(String value) {
        for (CreateMediaRequestLanguageCode o: CreateMediaRequestLanguageCode.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

