/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateLiveStreamRequestMaxResolution
 * 
 * <p>Max resolution can be used to control the maximum resolution your media is encoded, stored, and streamed at.
 */
public enum CreateLiveStreamRequestMaxResolution {
    ONE_THOUSAND_AND_EIGHTYP("1080p"),
    SEVEN_HUNDRED_AND_TWENTYP("720p"),
    FOUR_HUNDRED_AND_EIGHTYP("480p");

    @JsonValue
    private final String value;

    private CreateLiveStreamRequestMaxResolution(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateLiveStreamRequestMaxResolution> fromValue(String value) {
        for (CreateLiveStreamRequestMaxResolution o: CreateLiveStreamRequestMaxResolution.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

