/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.fastpix.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

public class Moderation {

    /**
     * Defines the type of input. Possible values include video, audio, av.
     */
    @JsonProperty("type")
    private CreateMediaRequestType type;

    @JsonCreator
    public Moderation(
            @JsonProperty("type") CreateMediaRequestType type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
    }

    /**
     * Defines the type of input. Possible values include video, audio, av.
     */
    @JsonIgnore
    public CreateMediaRequestType type() {
        return type;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Defines the type of input. Possible values include video, audio, av.
     */
    public Moderation withType(CreateMediaRequestType type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Moderation other = (Moderation) o;
        return 
            Objects.deepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Moderation.class,
                "type", type);
    }
    
    public final static class Builder {
 
        private CreateMediaRequestType type;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Defines the type of input. Possible values include video, audio, av.
         */
        public Builder type(CreateMediaRequestType type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }
        
        public Moderation build() {
            return new Moderation(
                type);
        }
    }
}
