/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.fastpix.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * PlaybackIdDomains
 * 
 * <p>Restrictions based on the originating domain of a request (e.g., whether requests from certain websites should be allowed or blocked).
 */
public class PlaybackIdDomains {

    /**
     * This sets the default behavior for domain access (either "allow" or "deny").
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("defaultPolicy")
    private Optional<? extends PlaybackIdDomainsDefaultPolicy> defaultPolicy;

    /**
     * A list of domains that are explicitly allowed access.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("allow")
    private Optional<? extends List<String>> allow;

    /**
     * A list of domains that are explicitly blocked from accessing the resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deny")
    private Optional<? extends List<String>> deny;

    @JsonCreator
    public PlaybackIdDomains(
            @JsonProperty("defaultPolicy") Optional<? extends PlaybackIdDomainsDefaultPolicy> defaultPolicy,
            @JsonProperty("allow") Optional<? extends List<String>> allow,
            @JsonProperty("deny") Optional<? extends List<String>> deny) {
        Utils.checkNotNull(defaultPolicy, "defaultPolicy");
        Utils.checkNotNull(allow, "allow");
        Utils.checkNotNull(deny, "deny");
        this.defaultPolicy = defaultPolicy;
        this.allow = allow;
        this.deny = deny;
    }
    
    public PlaybackIdDomains() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * This sets the default behavior for domain access (either "allow" or "deny").
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PlaybackIdDomainsDefaultPolicy> defaultPolicy() {
        return (Optional<PlaybackIdDomainsDefaultPolicy>) defaultPolicy;
    }

    /**
     * A list of domains that are explicitly allowed access.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> allow() {
        return (Optional<List<String>>) allow;
    }

    /**
     * A list of domains that are explicitly blocked from accessing the resource.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> deny() {
        return (Optional<List<String>>) deny;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * This sets the default behavior for domain access (either "allow" or "deny").
     */
    public PlaybackIdDomains withDefaultPolicy(PlaybackIdDomainsDefaultPolicy defaultPolicy) {
        Utils.checkNotNull(defaultPolicy, "defaultPolicy");
        this.defaultPolicy = Optional.ofNullable(defaultPolicy);
        return this;
    }

    /**
     * This sets the default behavior for domain access (either "allow" or "deny").
     */
    public PlaybackIdDomains withDefaultPolicy(Optional<? extends PlaybackIdDomainsDefaultPolicy> defaultPolicy) {
        Utils.checkNotNull(defaultPolicy, "defaultPolicy");
        this.defaultPolicy = defaultPolicy;
        return this;
    }

    /**
     * A list of domains that are explicitly allowed access.
     */
    public PlaybackIdDomains withAllow(List<String> allow) {
        Utils.checkNotNull(allow, "allow");
        this.allow = Optional.ofNullable(allow);
        return this;
    }

    /**
     * A list of domains that are explicitly allowed access.
     */
    public PlaybackIdDomains withAllow(Optional<? extends List<String>> allow) {
        Utils.checkNotNull(allow, "allow");
        this.allow = allow;
        return this;
    }

    /**
     * A list of domains that are explicitly blocked from accessing the resource.
     */
    public PlaybackIdDomains withDeny(List<String> deny) {
        Utils.checkNotNull(deny, "deny");
        this.deny = Optional.ofNullable(deny);
        return this;
    }

    /**
     * A list of domains that are explicitly blocked from accessing the resource.
     */
    public PlaybackIdDomains withDeny(Optional<? extends List<String>> deny) {
        Utils.checkNotNull(deny, "deny");
        this.deny = deny;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlaybackIdDomains other = (PlaybackIdDomains) o;
        return 
            Objects.deepEquals(this.defaultPolicy, other.defaultPolicy) &&
            Objects.deepEquals(this.allow, other.allow) &&
            Objects.deepEquals(this.deny, other.deny);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            defaultPolicy,
            allow,
            deny);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlaybackIdDomains.class,
                "defaultPolicy", defaultPolicy,
                "allow", allow,
                "deny", deny);
    }
    
    public final static class Builder {
 
        private Optional<? extends PlaybackIdDomainsDefaultPolicy> defaultPolicy = Optional.empty();
 
        private Optional<? extends List<String>> allow = Optional.empty();
 
        private Optional<? extends List<String>> deny = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * This sets the default behavior for domain access (either "allow" or "deny").
         */
        public Builder defaultPolicy(PlaybackIdDomainsDefaultPolicy defaultPolicy) {
            Utils.checkNotNull(defaultPolicy, "defaultPolicy");
            this.defaultPolicy = Optional.ofNullable(defaultPolicy);
            return this;
        }

        /**
         * This sets the default behavior for domain access (either "allow" or "deny").
         */
        public Builder defaultPolicy(Optional<? extends PlaybackIdDomainsDefaultPolicy> defaultPolicy) {
            Utils.checkNotNull(defaultPolicy, "defaultPolicy");
            this.defaultPolicy = defaultPolicy;
            return this;
        }

        /**
         * A list of domains that are explicitly allowed access.
         */
        public Builder allow(List<String> allow) {
            Utils.checkNotNull(allow, "allow");
            this.allow = Optional.ofNullable(allow);
            return this;
        }

        /**
         * A list of domains that are explicitly allowed access.
         */
        public Builder allow(Optional<? extends List<String>> allow) {
            Utils.checkNotNull(allow, "allow");
            this.allow = allow;
            return this;
        }

        /**
         * A list of domains that are explicitly blocked from accessing the resource.
         */
        public Builder deny(List<String> deny) {
            Utils.checkNotNull(deny, "deny");
            this.deny = Optional.ofNullable(deny);
            return this;
        }

        /**
         * A list of domains that are explicitly blocked from accessing the resource.
         */
        public Builder deny(Optional<? extends List<String>> deny) {
            Utils.checkNotNull(deny, "deny");
            this.deny = deny;
            return this;
        }
        
        public PlaybackIdDomains build() {
            return new PlaybackIdDomains(
                defaultPolicy,
                allow,
                deny);
        }
    }
}
