/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.fastpix.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public class PlaybackIdResponseData {

    /**
     * Unique identifier for the playbackId
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<String> id;

    /**
     * Determines if access to the streamed content is kept private or available to all.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("accessPolicy")
    private Optional<String> accessPolicy;

    @JsonCreator
    public PlaybackIdResponseData(
            @JsonProperty("id") Optional<String> id,
            @JsonProperty("accessPolicy") Optional<String> accessPolicy) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(accessPolicy, "accessPolicy");
        this.id = id;
        this.accessPolicy = accessPolicy;
    }
    
    public PlaybackIdResponseData() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * Unique identifier for the playbackId
     */
    @JsonIgnore
    public Optional<String> id() {
        return id;
    }

    /**
     * Determines if access to the streamed content is kept private or available to all.
     */
    @JsonIgnore
    public Optional<String> accessPolicy() {
        return accessPolicy;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique identifier for the playbackId
     */
    public PlaybackIdResponseData withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }

    /**
     * Unique identifier for the playbackId
     */
    public PlaybackIdResponseData withId(Optional<String> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * Determines if access to the streamed content is kept private or available to all.
     */
    public PlaybackIdResponseData withAccessPolicy(String accessPolicy) {
        Utils.checkNotNull(accessPolicy, "accessPolicy");
        this.accessPolicy = Optional.ofNullable(accessPolicy);
        return this;
    }

    /**
     * Determines if access to the streamed content is kept private or available to all.
     */
    public PlaybackIdResponseData withAccessPolicy(Optional<String> accessPolicy) {
        Utils.checkNotNull(accessPolicy, "accessPolicy");
        this.accessPolicy = accessPolicy;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlaybackIdResponseData other = (PlaybackIdResponseData) o;
        return 
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.accessPolicy, other.accessPolicy);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            id,
            accessPolicy);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlaybackIdResponseData.class,
                "id", id,
                "accessPolicy", accessPolicy);
    }
    
    public final static class Builder {
 
        private Optional<String> id = Optional.empty();
 
        private Optional<String> accessPolicy = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique identifier for the playbackId
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * Unique identifier for the playbackId
         */
        public Builder id(Optional<String> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * Determines if access to the streamed content is kept private or available to all.
         */
        public Builder accessPolicy(String accessPolicy) {
            Utils.checkNotNull(accessPolicy, "accessPolicy");
            this.accessPolicy = Optional.ofNullable(accessPolicy);
            return this;
        }

        /**
         * Determines if access to the streamed content is kept private or available to all.
         */
        public Builder accessPolicy(Optional<String> accessPolicy) {
            Utils.checkNotNull(accessPolicy, "accessPolicy");
            this.accessPolicy = accessPolicy;
            return this;
        }
        
        public PlaybackIdResponseData build() {
            return new PlaybackIdResponseData(
                id,
                accessPolicy);
        }
    }
}
