/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PlaybackIdAccessPolicy
 * 
 * <p>Determines if access to the streamed content is kept private or available to all.
 */
public enum PlaybackIdAccessPolicy {
    PUBLIC("public"),
    PRIVATE("private"),
    DRM("drm");

    @JsonValue
    private final String value;

    private PlaybackIdAccessPolicy(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PlaybackIdAccessPolicy> fromValue(String value) {
        for (PlaybackIdAccessPolicy o: PlaybackIdAccessPolicy.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

