/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.fastpix.sdk.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;

/**
 * SimulcastUpdateResponse
 * 
 * <p>Displays the result of the request.
 */
public class SimulcastUpdateResponse {

    /**
     * It demonstrates whether the request is successful or not.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("success")
    private Optional<Boolean> success;

    /**
     * Displays the result of the request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private Optional<? extends SimulcastUpdateResponseData> data;

    @JsonCreator
    public SimulcastUpdateResponse(
            @JsonProperty("success") Optional<Boolean> success,
            @JsonProperty("data") Optional<? extends SimulcastUpdateResponseData> data) {
        Utils.checkNotNull(success, "success");
        Utils.checkNotNull(data, "data");
        this.success = success;
        this.data = data;
    }
    
    public SimulcastUpdateResponse() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * It demonstrates whether the request is successful or not.
     */
    @JsonIgnore
    public Optional<Boolean> success() {
        return success;
    }

    /**
     * Displays the result of the request.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<SimulcastUpdateResponseData> data() {
        return (Optional<SimulcastUpdateResponseData>) data;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * It demonstrates whether the request is successful or not.
     */
    public SimulcastUpdateResponse withSuccess(boolean success) {
        Utils.checkNotNull(success, "success");
        this.success = Optional.ofNullable(success);
        return this;
    }

    /**
     * It demonstrates whether the request is successful or not.
     */
    public SimulcastUpdateResponse withSuccess(Optional<Boolean> success) {
        Utils.checkNotNull(success, "success");
        this.success = success;
        return this;
    }

    /**
     * Displays the result of the request.
     */
    public SimulcastUpdateResponse withData(SimulcastUpdateResponseData data) {
        Utils.checkNotNull(data, "data");
        this.data = Optional.ofNullable(data);
        return this;
    }

    /**
     * Displays the result of the request.
     */
    public SimulcastUpdateResponse withData(Optional<? extends SimulcastUpdateResponseData> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SimulcastUpdateResponse other = (SimulcastUpdateResponse) o;
        return 
            Objects.deepEquals(this.success, other.success) &&
            Objects.deepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            success,
            data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SimulcastUpdateResponse.class,
                "success", success,
                "data", data);
    }
    
    public final static class Builder {
 
        private Optional<Boolean> success = Optional.empty();
 
        private Optional<? extends SimulcastUpdateResponseData> data = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * It demonstrates whether the request is successful or not.
         */
        public Builder success(boolean success) {
            Utils.checkNotNull(success, "success");
            this.success = Optional.ofNullable(success);
            return this;
        }

        /**
         * It demonstrates whether the request is successful or not.
         */
        public Builder success(Optional<Boolean> success) {
            Utils.checkNotNull(success, "success");
            this.success = success;
            return this;
        }

        /**
         * Displays the result of the request.
         */
        public Builder data(SimulcastUpdateResponseData data) {
            Utils.checkNotNull(data, "data");
            this.data = Optional.ofNullable(data);
            return this;
        }

        /**
         * Displays the result of the request.
         */
        public Builder data(Optional<? extends SimulcastUpdateResponseData> data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }
        
        public SimulcastUpdateResponse build() {
            return new SimulcastUpdateResponse(
                success,
                data);
        }
    }
}
