/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SourceResolution
 * 
 * <p>The actual resolution of the uploaded media. This represents the native quality of the source media.
 */
public enum SourceResolution {
    TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP("2160p"),
    ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP("1440p"),
    ONE_THOUSAND_AND_EIGHTYP("1080p"),
    SEVEN_HUNDRED_AND_TWENTYP("720p"),
    FOUR_HUNDRED_AND_EIGHTYP("480p"),
    THREE_HUNDRED_AND_SIXTYP("360p");

    @JsonValue
    private final String value;

    private SourceResolution(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SourceResolution> fromValue(String value) {
        for (SourceResolution o: SourceResolution.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

