/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.GetVideoViewDetailsRequest;
import org.openapis.openapi.models.operations.ListByTopContentRequest;
import org.openapis.openapi.models.operations.ListByTopContentTimespan;
import org.openapis.openapi.models.operations.ListVideoViewsRequest;
import org.openapis.openapi.models.operations.async.GetVideoViewDetailsRequestBuilder;
import org.openapis.openapi.models.operations.async.GetVideoViewDetailsResponse;
import org.openapis.openapi.models.operations.async.ListByTopContentRequestBuilder;
import org.openapis.openapi.models.operations.async.ListByTopContentResponse;
import org.openapis.openapi.models.operations.async.ListVideoViewsRequestBuilder;
import org.openapis.openapi.models.operations.async.ListVideoViewsResponse;
import org.openapis.openapi.operations.GetVideoViewDetails;
import org.openapis.openapi.operations.ListByTopContent;
import org.openapis.openapi.operations.ListVideoViews;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;

/**
 * Operations involving views
 */
public class AsyncViews {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Views syncSDK;

    AsyncViews(Views syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Views sync() {
        return syncSDK;
    }


    /**
     * List video views
     * 
     * <p>Retrieves a list of video views that fall within the specified filters and have been completed
     * within a defined timespan. It lets you to analyse viewer interactions with your video content
     * effectively.
     * 
     * <p>#### How it works
     * 
     * <p>1. Send a `GET` request to this endpoint with the desired query parameters.
     * 
     * <p>2. Specify the timespan for which you want to retrieve the video views using the `timespan[]`
     * parameter.
     * 
     * <p>3. Filter the views based on dimensions such as browser, device, video title, viewer ID, etc., using
     * the `filterby[]` parameter. Get the dimensions by calling <a
     * href="https://docs.fastpix.io/reference/list_dimensions">list the dimensions</a> endpoint.
     * 
     * <p>4. Paginate the results using the `limit` and `offset` parameters.
     * 
     * <p>5. You can also filter by `viewerId`, `errorCode`, `orderBy` a specific field, and `sortOrder` in
     * ascending or descending order.
     * 
     * <p>6. You receive a response containing the list of video views matching the specified criteria.
     * 
     * <p>Each view in the response includes a unique `viewId`. You can use this `viewId` with the  <a
     * href="https://docs.fastpix.io/reference/get_video_view_details">Get Video View Details</a> endpoint
     * to retrieve more detailed information about that specific view.
     * 
     * <p>#### Example
     * 
     * <p>If you manage a video streaming service and want to analyze content performance across devices and
     * browsers. By calling the List Video Views endpoint with filters such as `browser_name` and
     * `device_type`, you can identify which platforms are most popular with your audience. This
     * information helps optimize content for widely used platforms and troubleshoot playback issues on
     * less common devices.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/audience-metrics">Audience metrics</a>, <a
     * href="https://docs.fastpix.io/docs/understand-dashboard-ui#1-views-dashboard">Views dashboard</a>
     * 
     * @return The async call builder
     */
    public ListVideoViewsRequestBuilder list() {
        return new ListVideoViewsRequestBuilder(sdkConfiguration);
    }

    /**
     * List video views
     * 
     * <p>Retrieves a list of video views that fall within the specified filters and have been completed
     * within a defined timespan. It lets you to analyse viewer interactions with your video content
     * effectively.
     * 
     * <p>#### How it works
     * 
     * <p>1. Send a `GET` request to this endpoint with the desired query parameters.
     * 
     * <p>2. Specify the timespan for which you want to retrieve the video views using the `timespan[]`
     * parameter.
     * 
     * <p>3. Filter the views based on dimensions such as browser, device, video title, viewer ID, etc., using
     * the `filterby[]` parameter. Get the dimensions by calling <a
     * href="https://docs.fastpix.io/reference/list_dimensions">list the dimensions</a> endpoint.
     * 
     * <p>4. Paginate the results using the `limit` and `offset` parameters.
     * 
     * <p>5. You can also filter by `viewerId`, `errorCode`, `orderBy` a specific field, and `sortOrder` in
     * ascending or descending order.
     * 
     * <p>6. You receive a response containing the list of video views matching the specified criteria.
     * 
     * <p>Each view in the response includes a unique `viewId`. You can use this `viewId` with the  <a
     * href="https://docs.fastpix.io/reference/get_video_view_details">Get Video View Details</a> endpoint
     * to retrieve more detailed information about that specific view.
     * 
     * <p>#### Example
     * 
     * <p>If you manage a video streaming service and want to analyze content performance across devices and
     * browsers. By calling the List Video Views endpoint with filters such as `browser_name` and
     * `device_type`, you can identify which platforms are most popular with your audience. This
     * information helps optimize content for widely used platforms and troubleshoot playback issues on
     * less common devices.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/audience-metrics">Audience metrics</a>, <a
     * href="https://docs.fastpix.io/docs/understand-dashboard-ui#1-views-dashboard">Views dashboard</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ListVideoViewsResponse>} - The async response
     */
    public CompletableFuture<ListVideoViewsResponse> list(@Nonnull ListVideoViewsRequest request) {
        return list(request, null);
    }

    /**
     * List video views
     * 
     * <p>Retrieves a list of video views that fall within the specified filters and have been completed
     * within a defined timespan. It lets you to analyse viewer interactions with your video content
     * effectively.
     * 
     * <p>#### How it works
     * 
     * <p>1. Send a `GET` request to this endpoint with the desired query parameters.
     * 
     * <p>2. Specify the timespan for which you want to retrieve the video views using the `timespan[]`
     * parameter.
     * 
     * <p>3. Filter the views based on dimensions such as browser, device, video title, viewer ID, etc., using
     * the `filterby[]` parameter. Get the dimensions by calling <a
     * href="https://docs.fastpix.io/reference/list_dimensions">list the dimensions</a> endpoint.
     * 
     * <p>4. Paginate the results using the `limit` and `offset` parameters.
     * 
     * <p>5. You can also filter by `viewerId`, `errorCode`, `orderBy` a specific field, and `sortOrder` in
     * ascending or descending order.
     * 
     * <p>6. You receive a response containing the list of video views matching the specified criteria.
     * 
     * <p>Each view in the response includes a unique `viewId`. You can use this `viewId` with the  <a
     * href="https://docs.fastpix.io/reference/get_video_view_details">Get Video View Details</a> endpoint
     * to retrieve more detailed information about that specific view.
     * 
     * <p>#### Example
     * 
     * <p>If you manage a video streaming service and want to analyze content performance across devices and
     * browsers. By calling the List Video Views endpoint with filters such as `browser_name` and
     * `device_type`, you can identify which platforms are most popular with your audience. This
     * information helps optimize content for widely used platforms and troubleshoot playback issues on
     * less common devices.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/audience-metrics">Audience metrics</a>, <a
     * href="https://docs.fastpix.io/docs/understand-dashboard-ui#1-views-dashboard">Views dashboard</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<ListVideoViewsResponse>} - The async response
     */
    public CompletableFuture<ListVideoViewsResponse> list(@Nonnull ListVideoViewsRequest request, @Nullable Options options) {
        AsyncRequestOperation<ListVideoViewsRequest, ListVideoViewsResponse> operation
              = new ListVideoViews.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get details of video view
     * 
     * <p>Retrieves detailed information about a specific video view using its unique `viewId`. This provides
     * insights into individual viewer interactions with your video content, helping you enhance user
     * experience and improve engagement with your videos.
     * 
     * <p>To use this endpoint, send `GET` request with the `viewId`. The response includes detailed metrics
     * and attributes related to the specified video view.
     * 
     * <p>#### Example
     * 
     * <p>If a developer receives a report of a poor viewing experience for a specific user. By using this
     * endpoint with the users `viewId`, the developer can retrieve metrics like buffering duration,
     * playback errors, and session length. This data allows the developer to pinpoint issues (such as poor
     * connectivity or a browser-specific problem) and take steps to improve the user experience.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/page/what-video-data-do-we-capture#/">What Video
     * Data do we capture?</a>
     * 
     * @return The async call builder
     */
    public GetVideoViewDetailsRequestBuilder getDetails() {
        return new GetVideoViewDetailsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get details of video view
     * 
     * <p>Retrieves detailed information about a specific video view using its unique `viewId`. This provides
     * insights into individual viewer interactions with your video content, helping you enhance user
     * experience and improve engagement with your videos.
     * 
     * <p>To use this endpoint, send `GET` request with the `viewId`. The response includes detailed metrics
     * and attributes related to the specified video view.
     * 
     * <p>#### Example
     * 
     * <p>If a developer receives a report of a poor viewing experience for a specific user. By using this
     * endpoint with the users `viewId`, the developer can retrieve metrics like buffering duration,
     * playback errors, and session length. This data allows the developer to pinpoint issues (such as poor
     * connectivity or a browser-specific problem) and take steps to improve the user experience.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/page/what-video-data-do-we-capture#/">What Video
     * Data do we capture?</a>
     * 
     * @param viewId Pass View Id
     * @return {@code CompletableFuture<GetVideoViewDetailsResponse>} - The async response
     */
    public CompletableFuture<GetVideoViewDetailsResponse> getDetails(@Nonnull String viewId) {
        return getDetails(viewId, null);
    }

    /**
     * Get details of video view
     * 
     * <p>Retrieves detailed information about a specific video view using its unique `viewId`. This provides
     * insights into individual viewer interactions with your video content, helping you enhance user
     * experience and improve engagement with your videos.
     * 
     * <p>To use this endpoint, send `GET` request with the `viewId`. The response includes detailed metrics
     * and attributes related to the specified video view.
     * 
     * <p>#### Example
     * 
     * <p>If a developer receives a report of a poor viewing experience for a specific user. By using this
     * endpoint with the users `viewId`, the developer can retrieve metrics like buffering duration,
     * playback errors, and session length. This data allows the developer to pinpoint issues (such as poor
     * connectivity or a browser-specific problem) and take steps to improve the user experience.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/page/what-video-data-do-we-capture#/">What Video
     * Data do we capture?</a>
     * 
     * @param viewId Pass View Id
     * @param options additional options
     * @return {@code CompletableFuture<GetVideoViewDetailsResponse>} - The async response
     */
    public CompletableFuture<GetVideoViewDetailsResponse> getDetails(@Nonnull String viewId, @Nullable Options options) {
        GetVideoViewDetailsRequest request = new GetVideoViewDetailsRequest(viewId);
        AsyncRequestOperation<GetVideoViewDetailsRequest, GetVideoViewDetailsResponse> operation
              = new GetVideoViewDetails.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * List by top content
     * 
     * <p>Retrieves a list of the top video views that fall within the specified filters and have been
     * completed within a defined timespan. It lets you to identify the most popular content based on
     * viewer interactions.
     * 
     * <p>#### How it works
     * 
     * <p>1. Send a `GET` request to this endpoint with the desired query parameters.
     * 
     * <p>2. Specify the timespan for which you want to retrieve the top content using the `timespan[]`
     * parameter.
     * 
     * <p>3. Filter the views based on dimensions such as browser, device, video title, etc., using the
     * `filterby[]` parameter.
     * 
     * <p>4. You can use `Limit` to control number of top views returned.
     * 
     * <p>5. You receive a response containing the list of top video views matching the specified criteria.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/page/how-to-get-top-performing-content">Get
     * top-performing content</a>
     * 
     * @return The async call builder
     */
    public ListByTopContentRequestBuilder listByTopContent() {
        return new ListByTopContentRequestBuilder(sdkConfiguration);
    }

    /**
     * List by top content
     * 
     * <p>Retrieves a list of the top video views that fall within the specified filters and have been
     * completed within a defined timespan. It lets you to identify the most popular content based on
     * viewer interactions.
     * 
     * <p>#### How it works
     * 
     * <p>1. Send a `GET` request to this endpoint with the desired query parameters.
     * 
     * <p>2. Specify the timespan for which you want to retrieve the top content using the `timespan[]`
     * parameter.
     * 
     * <p>3. Filter the views based on dimensions such as browser, device, video title, etc., using the
     * `filterby[]` parameter.
     * 
     * <p>4. You can use `Limit` to control number of top views returned.
     * 
     * <p>5. You receive a response containing the list of top video views matching the specified criteria.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/page/how-to-get-top-performing-content">Get
     * top-performing content</a>
     * 
     * @return {@code CompletableFuture<ListByTopContentResponse>} - The async response
     */
    public CompletableFuture<ListByTopContentResponse> listByTopContentDirect() {
        return listByTopContent(
                null, null, null,
                null);
    }

    /**
     * List by top content
     * 
     * <p>Retrieves a list of the top video views that fall within the specified filters and have been
     * completed within a defined timespan. It lets you to identify the most popular content based on
     * viewer interactions.
     * 
     * <p>#### How it works
     * 
     * <p>1. Send a `GET` request to this endpoint with the desired query parameters.
     * 
     * <p>2. Specify the timespan for which you want to retrieve the top content using the `timespan[]`
     * parameter.
     * 
     * <p>3. Filter the views based on dimensions such as browser, device, video title, etc., using the
     * `filterby[]` parameter.
     * 
     * <p>4. You can use `Limit` to control number of top views returned.
     * 
     * <p>5. You receive a response containing the list of top video views matching the specified criteria.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/page/how-to-get-top-performing-content">Get
     * top-performing content</a>
     * 
     * @param timespan This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
     *         
     *         **Accepted formats are:**
     *         
     *         array of epoch timestamps for example  
     *         `timespan[]=1498867200&amp;timespan[]=1498953600`
     *         
     *         duration string for example  
     *         `timespan[]=24:hours` or `timespan[]=7:days`
     *         
     * @param filterby Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass "!" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
     *         Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]
     *         
     * @param limit Pass the limit to display only the rows specified by the value.
     *         
     * @param options additional options
     * @return {@code CompletableFuture<ListByTopContentResponse>} - The async response
     */
    public CompletableFuture<ListByTopContentResponse> listByTopContent(
            @Nullable ListByTopContentTimespan timespan, @Nullable String filterby,
            @Nullable Long limit, @Nullable Options options) {
        ListByTopContentRequest request = new ListByTopContentRequest(timespan, filterby, limit);
        AsyncRequestOperation<ListByTopContentRequest, ListByTopContentResponse> operation
              = new ListByTopContent.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
