/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.GetLiveStreamPlaybackIdRequest;
import org.openapis.openapi.models.operations.async.GetLiveStreamPlaybackIdRequestBuilder;
import org.openapis.openapi.models.operations.async.GetLiveStreamPlaybackIdResponse;
import org.openapis.openapi.operations.GetLiveStreamPlaybackId;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncLivePlaybacks {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final LivePlaybacks syncSDK;

    AsyncLivePlaybacks(LivePlaybacks syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public LivePlaybacks sync() {
        return syncSDK;
    }


    /**
     * Get playbackId details
     * 
     * <p>Retrieves details for an existing playback ID. When you provide the playbackId returned from a
     * previous stream or playback creation request, FastPix returns the associated playback information,
     * including the access policy.
     * 
     * <p>#### Example
     * A developer needs to confirm the access policy of the playback ID to ensure whether the stream is
     * public or private for viewers.
     * 
     * @return The async call builder
     */
    public GetLiveStreamPlaybackIdRequestBuilder getPlaybackIdDetails() {
        return new GetLiveStreamPlaybackIdRequestBuilder(sdkConfiguration);
    }

    /**
     * Get playbackId details
     * 
     * <p>Retrieves details for an existing playback ID. When you provide the playbackId returned from a
     * previous stream or playback creation request, FastPix returns the associated playback information,
     * including the access policy.
     * 
     * <p>#### Example
     * A developer needs to confirm the access policy of the playback ID to ensure whether the stream is
     * public or private for viewers.
     * 
     * @param streamId After creating a new live stream, FastPix assigns a unique identifier to the stream.
     * @param playbackId After creating a new playbackId, FastPix assigns a unique identifier to the playback.
     * @return {@code CompletableFuture<GetLiveStreamPlaybackIdResponse>} - The async response
     */
    public CompletableFuture<GetLiveStreamPlaybackIdResponse> getPlaybackIdDetails(@Nonnull String streamId, @Nonnull String playbackId) {
        return getPlaybackIdDetails(streamId, playbackId, null);
    }

    /**
     * Get playbackId details
     * 
     * <p>Retrieves details for an existing playback ID. When you provide the playbackId returned from a
     * previous stream or playback creation request, FastPix returns the associated playback information,
     * including the access policy.
     * 
     * <p>#### Example
     * A developer needs to confirm the access policy of the playback ID to ensure whether the stream is
     * public or private for viewers.
     * 
     * @param streamId After creating a new live stream, FastPix assigns a unique identifier to the stream.
     * @param playbackId After creating a new playbackId, FastPix assigns a unique identifier to the playback.
     * @param options additional options
     * @return {@code CompletableFuture<GetLiveStreamPlaybackIdResponse>} - The async response
     */
    public CompletableFuture<GetLiveStreamPlaybackIdResponse> getPlaybackIdDetails(
            @Nonnull String streamId, @Nonnull String playbackId,
            @Nullable Options options) {
        GetLiveStreamPlaybackIdRequest request = new GetLiveStreamPlaybackIdRequest(streamId, playbackId);
        AsyncRequestOperation<GetLiveStreamPlaybackIdRequest, GetLiveStreamPlaybackIdResponse> operation
              = new GetLiveStreamPlaybackId.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
