/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.GetDrmConfigurationByIdRequest;
import org.openapis.openapi.models.operations.GetDrmConfigurationRequest;
import org.openapis.openapi.models.operations.async.GetDrmConfigurationByIdRequestBuilder;
import org.openapis.openapi.models.operations.async.GetDrmConfigurationByIdResponse;
import org.openapis.openapi.models.operations.async.GetDrmConfigurationRequestBuilder;
import org.openapis.openapi.models.operations.async.GetDrmConfigurationResponse;
import org.openapis.openapi.operations.GetDrmConfiguration;
import org.openapis.openapi.operations.GetDrmConfigurationById;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class AsyncDrmConfigurations {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final DrmConfigurations syncSDK;

    AsyncDrmConfigurations(DrmConfigurations syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public DrmConfigurations sync() {
        return syncSDK;
    }


    /**
     * Get list of DRM configuration IDs
     * 
     * <p>This endpoint retrieves the DRM configuration (DRM ID) associated with a workspace. It returns a
     * list of DRM configurations, identified by a unique DRM ID, which is used for creating DRM encrypted
     * asset.
     * 
     * <p>**How it works:**
     * 1. Make a GET request to this endpoint.
     * 2. Optionally use the `offset` and `limit` query parameters to paginate through the list of DRM
     * configurations.
     * 3. The response includes a list of DRM IDs and pagination metadata.
     * 
     * <p>**Example:**
     * A media service provider may retrieve DRM configuration for a workspace to create DRM content.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/secure-playback-with-drm">Manage DRM
     * configuration</a>
     * 
     * @return The async call builder
     */
    public GetDrmConfigurationRequestBuilder list() {
        return new GetDrmConfigurationRequestBuilder(sdkConfiguration);
    }

    /**
     * Get list of DRM configuration IDs
     * 
     * <p>This endpoint retrieves the DRM configuration (DRM ID) associated with a workspace. It returns a
     * list of DRM configurations, identified by a unique DRM ID, which is used for creating DRM encrypted
     * asset.
     * 
     * <p>**How it works:**
     * 1. Make a GET request to this endpoint.
     * 2. Optionally use the `offset` and `limit` query parameters to paginate through the list of DRM
     * configurations.
     * 3. The response includes a list of DRM IDs and pagination metadata.
     * 
     * <p>**Example:**
     * A media service provider may retrieve DRM configuration for a workspace to create DRM content.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/secure-playback-with-drm">Manage DRM
     * configuration</a>
     * 
     * @return {@code CompletableFuture<GetDrmConfigurationResponse>} - The async response
     */
    public CompletableFuture<GetDrmConfigurationResponse> listDirect() {
        return list(null, null, null);
    }

    /**
     * Get list of DRM configuration IDs
     * 
     * <p>This endpoint retrieves the DRM configuration (DRM ID) associated with a workspace. It returns a
     * list of DRM configurations, identified by a unique DRM ID, which is used for creating DRM encrypted
     * asset.
     * 
     * <p>**How it works:**
     * 1. Make a GET request to this endpoint.
     * 2. Optionally use the `offset` and `limit` query parameters to paginate through the list of DRM
     * configurations.
     * 3. The response includes a list of DRM IDs and pagination metadata.
     * 
     * <p>**Example:**
     * A media service provider may retrieve DRM configuration for a workspace to create DRM content.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/secure-playback-with-drm">Manage DRM
     * configuration</a>
     * 
     * @param offset Offset determines the starting point for data retrieval within a paginated list.
     * @param limit Limit specifies the maximum number of items to display per page.
     * @param options additional options
     * @return {@code CompletableFuture<GetDrmConfigurationResponse>} - The async response
     */
    public CompletableFuture<GetDrmConfigurationResponse> list(
            @Nullable Long offset, @Nullable Long limit,
            @Nullable Options options) {
        GetDrmConfigurationRequest request = new GetDrmConfigurationRequest(offset, limit);
        AsyncRequestOperation<GetDrmConfigurationRequest, GetDrmConfigurationResponse> operation
              = new GetDrmConfiguration.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get DRM configuration by ID
     * 
     * <p>This endpoint retrieves a DRM configuration ID. It is used to fetch the DRM-related ID for a
     * workspace, typically required when validating or applying DRM policies to video assets.
     * 
     * <p>**How it works:**
     * 1. Make a GET request to this endpoint, replacing `{drmConfigurationId}` with the UUID of the DRM
     * configuration.
     * 2. The response contains the associated DRM configuration ID.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/secure-playback-with-drm">Manage DRM
     * configuration</a>
     * 
     * @return The async call builder
     */
    public GetDrmConfigurationByIdRequestBuilder getById() {
        return new GetDrmConfigurationByIdRequestBuilder(sdkConfiguration);
    }

    /**
     * Get DRM configuration by ID
     * 
     * <p>This endpoint retrieves a DRM configuration ID. It is used to fetch the DRM-related ID for a
     * workspace, typically required when validating or applying DRM policies to video assets.
     * 
     * <p>**How it works:**
     * 1. Make a GET request to this endpoint, replacing `{drmConfigurationId}` with the UUID of the DRM
     * configuration.
     * 2. The response contains the associated DRM configuration ID.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/secure-playback-with-drm">Manage DRM
     * configuration</a>
     * 
     * @param drmConfigurationId The unique identifier of the DRM configuration.
     * @return {@code CompletableFuture<GetDrmConfigurationByIdResponse>} - The async response
     */
    public CompletableFuture<GetDrmConfigurationByIdResponse> getById(@Nonnull String drmConfigurationId) {
        return getById(drmConfigurationId, null);
    }

    /**
     * Get DRM configuration by ID
     * 
     * <p>This endpoint retrieves a DRM configuration ID. It is used to fetch the DRM-related ID for a
     * workspace, typically required when validating or applying DRM policies to video assets.
     * 
     * <p>**How it works:**
     * 1. Make a GET request to this endpoint, replacing `{drmConfigurationId}` with the UUID of the DRM
     * configuration.
     * 2. The response contains the associated DRM configuration ID.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/secure-playback-with-drm">Manage DRM
     * configuration</a>
     * 
     * @param drmConfigurationId The unique identifier of the DRM configuration.
     * @param options additional options
     * @return {@code CompletableFuture<GetDrmConfigurationByIdResponse>} - The async response
     */
    public CompletableFuture<GetDrmConfigurationByIdResponse> getById(@Nonnull String drmConfigurationId, @Nullable Options options) {
        GetDrmConfigurationByIdRequest request = new GetDrmConfigurationByIdRequest(drmConfigurationId);
        AsyncRequestOperation<GetDrmConfigurationByIdRequest, GetDrmConfigurationByIdResponse> operation
              = new GetDrmConfigurationById.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
