/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package org.openapis.openapi;

import java.lang.String;
import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;
import org.openapis.openapi.utils.HTTPClient;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.utils.FastpixHTTPClient;
import org.openapis.openapi.utils.Utils;

/**
 * FASTPIX API'S: FastPix provides a comprehensive set of APIs that enable developers to manage both
 * **on-demand media (video/audio)** and **live streaming experiences**, with built-in security
 * features through **cryptographic signing keys**. These APIs cover the full lifecycle of content
 * creation, management, distribution, playback, and secure access, making them ideal for building
 * scalable video-first applications.
 * ### Media APIs (Video &amp; Audio on Demand)
 * The **Media APIs** allow developers to create, retrieve, update, and delete media files, as well as
 * manage metadata, playback settings, and additional tracks such as audio or subtitles. With these
 * endpoints, developers can:
 * - Upload videos directly or create media from URLs. - Manage playback permissions and configure
 * playback IDs.
 * 
 * <p>- Add multilingual audio or subtitle tracks for global audiences. - Build robust video-on-demand
 * (VOD) and audio-on-demand (AOD) libraries.
 * **Use case scenarios**   - **Video-on-Demand Platforms:** Manage large content libraries for
 * streaming services. - **E-Learning Solutions:** Upload and organize lecture videos, metadata, and
 * playback settings.
 * 
 * <p>- **Multilingual Content Delivery:** Add multiple language tracks or subtitles to serve global
 * users.
 * ### Live Stream APIs
 * The **Live Stream APIs** simplify the process of creating, managing, and distributing live content.
 * Developers can initiate broadcasts, configure stream settings, and extend streams to external
 * platforms through simulcasting.
 * 
 * <p>These endpoints also support real-time interaction and customization of live events.
 * - Start and manage live broadcasts programmatically. - Control stream metadata, privacy, and
 * playback options.
 * 
 * <p>- Simulcast to platforms like YouTube, Facebook, or Twitch. - Update stream details and manage live
 * playback IDs in real time.
 * **Use case scenarios**   - **Event Broadcasting:** Enable organizers to set up live streams for
 * conferences, concerts, or webinars. - **Creator Platforms:** Provide streamers with tools for
 * broadcasting gameplay, tutorials, or vlogs with simulcasting support.
 * 
 * <p>- **Corporate Streaming:** Deliver secure internal town halls or meetings with privacy and playback
 * controls.
 * ### Video Data APIs
 * The **Video Data APIs** Provide insights into viewer interactions, performance metrics, and playback
 * errors to optimize content delivery and user experience.
 * 
 * <p>- Track video views, unique viewers, and engagement metrics
 * - Identify top-performing content and usage patterns
 * - Break down data by browser, device, or geography
 * - Detect playback errors and performance issues
 * - Enable data-driven content strategy decisions
 * 
 * <p>**Use case scenarios**
 * - Analytics Dashboards: Monitor performance across content libraries
 * - Quality Monitoring: Diagnose and resolve playback issues
 * - Content Strategy Optimization: Identify high-value content
 * - User Behavior Insights: Understand audience interactions
 * 
 * <p>### Signing Keys
 * FastPix also provides endpoints for managing **cryptographic signing keys**, which are essential for
 * securely signing and verifying tokens, such as JSON Web Tokens (JWTs). These keys are critical for
 * authenticating and authorizing API requests, as well as for protecting access to media assets.
 * - **Private key:** Used to create digital signatures (kept secret). - **Public key:** Used to verify
 * digital signatures (shared for verification).
 * By rotating and managing signing keys regularly, developers can maintain strong security practices
 * and prevent unauthorized access.
 * **Use case scenarios**   - **Token-based authentication:** Validate user access to premium or
 * subscription-based content. - **Key rotation:** Regularly rotate keys to reduce risk of compromise.
 * 
 * <p>- **Protect intellectual property:** Prevent unauthorized distribution of valuable media assets. -
 * **Control usage:** Restrict access to specific users, groups, or contexts.
 * 
 * <p>- **Prevent tampering:** Ensure requested assets have not been modified. - **Time-bound access:**
 * Enable signed URLs with expiration for controlled viewing windows.
 */
public class Fastpix {
    private static final Headers _headers = Headers.EMPTY;


    /**
     * SERVERS contains the list of server urls available to the SDK.
     */
    public static final String[] SERVERS = {
        /*
         * FastPix Video APIs
         */
        "https://api.fastpix.io/v1/",
    };


    private final InputVideos inputVideos;


    private final ManageVideos manageVideos;


    private final Videos videos;


    private final AiFeatures aiFeatures;


    private final InVideoAiFeatures inVideoAiFeatures;

    /**
     * Operations for video playback management
     */
    private final Playback playback;


    private final Playlists playlists;

    /**
     * Operations for playlist management
     */
    private final Playlist playlist;


    private final DrmConfigurations drmConfigurations;


    private final Streams streams;


    private final ManageLiveStreams manageLiveStreams;


    private final ManageLiveStream manageLiveStream;


    private final LiveStream liveStream;


    private final LivePlayback livePlayback;


    private final LivePlaybacks livePlaybacks;


    private final SimulcastStream simulcastStream;


    private final SimulcastStreams simulcastStreams;


    private final Simulcasts simulcasts;


    private final SigningKeys signingKeys;

    /**
     * Operations involving views
     */
    private final Views views;

    /**
     * Operations involving dimensions
     */
    private final Dimensions dimensions;

    /**
     * Operations involving metrics
     */
    private final Metrics metrics;

    /**
     * Operations involving errors
     */
    private final Errors errors;


    public InputVideos inputVideos() {
        return inputVideos;
    }


    public ManageVideos manageVideos() {
        return manageVideos;
    }


    public Videos videos() {
        return videos;
    }


    public AiFeatures aiFeatures() {
        return aiFeatures;
    }


    public InVideoAiFeatures inVideoAiFeatures() {
        return inVideoAiFeatures;
    }

    /**
     * Operations for video playback management
     */
    public Playback playback() {
        return playback;
    }


    public Playlists playlists() {
        return playlists;
    }

    /**
     * Operations for playlist management
     */
    public Playlist playlist() {
        return playlist;
    }


    public DrmConfigurations drmConfigurations() {
        return drmConfigurations;
    }


    public Streams streams() {
        return streams;
    }


    public ManageLiveStreams manageLiveStreams() {
        return manageLiveStreams;
    }


    public ManageLiveStream manageLiveStream() {
        return manageLiveStream;
    }


    public LiveStream liveStream() {
        return liveStream;
    }


    public LivePlayback livePlayback() {
        return livePlayback;
    }


    public LivePlaybacks livePlaybacks() {
        return livePlaybacks;
    }


    public SimulcastStream simulcastStream() {
        return simulcastStream;
    }


    public SimulcastStreams simulcastStreams() {
        return simulcastStreams;
    }


    public Simulcasts simulcasts() {
        return simulcasts;
    }


    public SigningKeys signingKeys() {
        return signingKeys;
    }

    /**
     * Operations involving views
     */
    public Views views() {
        return views;
    }

    /**
     * Operations involving dimensions
     */
    public Dimensions dimensions() {
        return dimensions;
    }

    /**
     * Operations involving metrics
     */
    public Metrics metrics() {
        return metrics;
    }

    /**
     * Operations involving errors
     */
    public Errors errors() {
        return errors;
    }
    private final AsyncFastpix asyncSDK;

    /**
     * The Builder class allows the configuration of a new instance of the SDK.
     */
    public static class Builder {

        private final SDKConfiguration sdkConfiguration = new SDKConfiguration();
        private String serverUrl;
        private String server;
        

        private Builder() {
        }

        /**
         * Allows the default HTTP client to be overridden with a custom implementation.
         *
         * @param client The HTTP client to use for all requests.
         * @return The builder instance.
         */
        public Builder client(HTTPClient client) {
            this.sdkConfiguration.setClient(client);
            return this;
        }
        
        /**
         * Configures the SDK to use the provided security details.
         *
         * @param security The security details to use for all requests. Can be {@code null}.
         * @return The builder instance.
         */
        public Builder security(org.openapis.openapi.models.components.Security security) {
            this.sdkConfiguration.setSecuritySource(SecuritySource.of(security));
            return this;
        }

        /**
         * Configures the SDK to use a custom security source.
         *
         * @param securitySource The security source to use for all requests.
         * @return The builder instance.
         */
        public Builder securitySource(SecuritySource securitySource) {
            Utils.checkNotNull(securitySource, "securitySource");
            this.sdkConfiguration.setSecuritySource(securitySource);
            return this;
        }
        
        /**
         * Overrides the default server URL.
         *
         * @param serverUrl The server URL to use for all requests.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl) {
            this.serverUrl = serverUrl;
            return this;
        }

        /**
         * Overrides the default server URL with a templated URL populated with the provided parameters.
         *
         * @param serverUrl The server URL to use for all requests.
         * @param params The parameters to use when templating the URL.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl, Map<String, String> params) {
            this.serverUrl = Utils.templateUrl(serverUrl, params);
            return this;
        }
        
        /**
         * Overrides the default server by index.
         *
         * @param serverIdx The server to use for all requests.
         * @return The builder instance.
         */
        public Builder serverIndex(int serverIdx) {
            this.sdkConfiguration.setServerIdx(serverIdx);
            this.serverUrl= SERVERS[serverIdx];
            return this;
        }
        
        /**
         * Overrides the default configuration for retries
         *
         * @param retryConfig The retry configuration to use for all requests.
         * @return The builder instance.
         */
        public Builder retryConfig(RetryConfig retryConfig) {
            this.sdkConfiguration.setRetryConfig(Optional.of(retryConfig));
            return this;
        }

        /**
         * Enables debug logging for HTTP requests and responses, including JSON body content.
         * <p>
         * Convenience method that calls {@link HTTPClient#enableDebugLogging(boolean)}.
         * {@link FastpixHTTPClient} honors this setting. If you are using a custom HTTP client,
         * it is up to the custom client to honor this setting.
         * </p>
         *
         * @param enabled Whether to enable debug logging.
         * @return The builder instance.
         */
        public Builder enableHTTPDebugLogging(boolean enabled) {
            this.sdkConfiguration.client().enableDebugLogging(enabled);
            return this;
        }

        // Visible for testing, may be accessed via reflection in tests
        Builder _hooks(org.openapis.openapi.utils.Hooks hooks) {
            sdkConfiguration.setHooks(hooks);  
            return this;  
        }
        
        // Visible for testing, may be accessed via reflection in tests
        Builder _hooks(Consumer<? super org.openapis.openapi.utils.Hooks> consumer) {
            consumer.accept(sdkConfiguration.hooks());
            return this;    
        }

        /**
         * Builds a new instance of the SDK.
         *
         * @return The SDK instance.
         */
        public Fastpix build() {
            if (serverUrl == null || serverUrl.isBlank()) {
                serverUrl = SERVERS[0];
                sdkConfiguration.setServerIdx(0);
            }
            sdkConfiguration.setServerUrl(serverUrl);
            return new Fastpix(sdkConfiguration);
        }
    }

    /**
     * Get a new instance of the SDK builder to configure a new instance of the SDK.
     *
     * @return The SDK builder instance.
     */
    public static Builder builder() {
        return new Builder();
    }

    public Fastpix(SDKConfiguration sdkConfiguration) {
        sdkConfiguration.initialize();
        this.inputVideos = new InputVideos(sdkConfiguration);
        this.manageVideos = new ManageVideos(sdkConfiguration);
        this.videos = new Videos(sdkConfiguration);
        this.aiFeatures = new AiFeatures(sdkConfiguration);
        this.inVideoAiFeatures = new InVideoAiFeatures(sdkConfiguration);
        this.playback = new Playback(sdkConfiguration);
        this.playlists = new Playlists(sdkConfiguration);
        this.playlist = new Playlist(sdkConfiguration);
        this.drmConfigurations = new DrmConfigurations(sdkConfiguration);
        this.streams = new Streams(sdkConfiguration);
        this.manageLiveStreams = new ManageLiveStreams(sdkConfiguration);
        this.manageLiveStream = new ManageLiveStream(sdkConfiguration);
        this.liveStream = new LiveStream(sdkConfiguration);
        this.livePlayback = new LivePlayback(sdkConfiguration);
        this.livePlaybacks = new LivePlaybacks(sdkConfiguration);
        this.simulcastStream = new SimulcastStream(sdkConfiguration);
        this.simulcastStreams = new SimulcastStreams(sdkConfiguration);
        this.simulcasts = new Simulcasts(sdkConfiguration);
        this.signingKeys = new SigningKeys(sdkConfiguration);
        this.views = new Views(sdkConfiguration);
        this.dimensions = new Dimensions(sdkConfiguration);
        this.metrics = new Metrics(sdkConfiguration);
        this.errors = new Errors(sdkConfiguration);
        sdkConfiguration = sdkConfiguration.hooks().sdkInit(sdkConfiguration);
        this.asyncSDK = new AsyncFastpix(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncFastpix async() {
        return asyncSDK;
    }

}
