/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import org.openapis.openapi.models.components.SimulcastRequest;
import org.openapis.openapi.models.operations.CreateSimulcastOfStreamRequest;
import org.openapis.openapi.models.operations.CreateSimulcastOfStreamRequestBuilder;
import org.openapis.openapi.models.operations.CreateSimulcastOfStreamResponse;
import org.openapis.openapi.operations.CreateSimulcastOfStream;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Options;


public class SimulcastStream {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSimulcastStream asyncSDK;

    SimulcastStream(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSimulcastStream(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSimulcastStream async() {
        return asyncSDK;
    }

    /**
     * Create a simulcast
     * 
     * <p>Creates a simulcast for a parent live stream. Simulcasting allows you to broadcast a live stream to
     * multiple social platforms simultaneously (for example, YouTube, Facebook, or Twitch). This helps
     * expand your audience reach across platforms.
     * 
     * <p>A simulcast can only be created when the parent live stream is in the idle state (not currently live
     * or disabled). Only one simulcast target can be created per API call.
     * #### How it works
     * 
     * <p>1. Change to: When you call this endpoint, provide the parent `streamId` along with the simulcast
     * target details (such as platform and credentials). The API returns a unique `simulcastId`, which you
     * can use to manage the simulcast later.
     * 
     * <p>2. To notify your application about the status of simulcast related events check for the <a
     * href="https://docs.fastpix.io/docs/webhooks-collection#simulcast-target-events">webhooks for
     * simulcast</a> target events.
     * 
     * <p>#### Example
     * An event manager sets up a live stream for a virtual conference and wants to simulcast the stream on
     * YouTube and Facebook Live. They first create the primary live stream in FastPix, ensuring it's in
     * the idle state. Then, they use the API to create a simulcast target for YouTube.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/simulcast-to-3rd-party-platforms">Simulcast to
     * 3rd party platforms</a>
     * 
     * @return The call builder
     */
    public CreateSimulcastOfStreamRequestBuilder create() {
        return new CreateSimulcastOfStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a simulcast
     * 
     * <p>Creates a simulcast for a parent live stream. Simulcasting allows you to broadcast a live stream to
     * multiple social platforms simultaneously (for example, YouTube, Facebook, or Twitch). This helps
     * expand your audience reach across platforms.
     * 
     * <p>A simulcast can only be created when the parent live stream is in the idle state (not currently live
     * or disabled). Only one simulcast target can be created per API call.
     * #### How it works
     * 
     * <p>1. Change to: When you call this endpoint, provide the parent `streamId` along with the simulcast
     * target details (such as platform and credentials). The API returns a unique `simulcastId`, which you
     * can use to manage the simulcast later.
     * 
     * <p>2. To notify your application about the status of simulcast related events check for the <a
     * href="https://docs.fastpix.io/docs/webhooks-collection#simulcast-target-events">webhooks for
     * simulcast</a> target events.
     * 
     * <p>#### Example
     * An event manager sets up a live stream for a virtual conference and wants to simulcast the stream on
     * YouTube and Facebook Live. They first create the primary live stream in FastPix, ensuring it's in
     * the idle state. Then, they use the API to create a simulcast target for YouTube.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/simulcast-to-3rd-party-platforms">Simulcast to
     * 3rd party platforms</a>
     * 
     * @param streamId After creating a new live stream, FastPix assigns a unique identifier to the stream.
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateSimulcastOfStreamResponse create(@Nonnull String streamId, @Nonnull SimulcastRequest body) {
        return create(streamId, body, null);
    }

    /**
     * Create a simulcast
     * 
     * <p>Creates a simulcast for a parent live stream. Simulcasting allows you to broadcast a live stream to
     * multiple social platforms simultaneously (for example, YouTube, Facebook, or Twitch). This helps
     * expand your audience reach across platforms.
     * 
     * <p>A simulcast can only be created when the parent live stream is in the idle state (not currently live
     * or disabled). Only one simulcast target can be created per API call.
     * #### How it works
     * 
     * <p>1. Change to: When you call this endpoint, provide the parent `streamId` along with the simulcast
     * target details (such as platform and credentials). The API returns a unique `simulcastId`, which you
     * can use to manage the simulcast later.
     * 
     * <p>2. To notify your application about the status of simulcast related events check for the <a
     * href="https://docs.fastpix.io/docs/webhooks-collection#simulcast-target-events">webhooks for
     * simulcast</a> target events.
     * 
     * <p>#### Example
     * An event manager sets up a live stream for a virtual conference and wants to simulcast the stream on
     * YouTube and Facebook Live. They first create the primary live stream in FastPix, ensuring it's in
     * the idle state. Then, they use the API to create a simulcast target for YouTube.
     * 
     * <p>Related guide: <a href="https://docs.fastpix.io/docs/simulcast-to-3rd-party-platforms">Simulcast to
     * 3rd party platforms</a>
     * 
     * @param streamId After creating a new live stream, FastPix assigns a unique identifier to the stream.
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateSimulcastOfStreamResponse create(
            @Nonnull String streamId, @Nonnull SimulcastRequest body,
            @Nullable Options options) {
        CreateSimulcastOfStreamRequest request = new CreateSimulcastOfStreamRequest(streamId, body);
        RequestOperation<CreateSimulcastOfStreamRequest, CreateSimulcastOfStreamResponse> operation
              = new CreateSimulcastOfStream.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
