/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package io.fastpix.sdk;

import static io.fastpix.sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import io.fastpix.sdk.models.components.PlaybackIdRequest;
import io.fastpix.sdk.models.operations.CreatePlaybackIdOfStreamRequest;
import io.fastpix.sdk.models.operations.DeletePlaybackIdOfStreamRequest;
import io.fastpix.sdk.models.operations.async.CreatePlaybackIdOfStreamRequestBuilder;
import io.fastpix.sdk.models.operations.async.CreatePlaybackIdOfStreamResponse;
import io.fastpix.sdk.models.operations.async.DeletePlaybackIdOfStreamRequestBuilder;
import io.fastpix.sdk.models.operations.async.DeletePlaybackIdOfStreamResponse;
import io.fastpix.sdk.operations.CreatePlaybackIdOfStream;
import io.fastpix.sdk.operations.DeletePlaybackIdOfStream;
import io.fastpix.sdk.utils.Headers;
import io.fastpix.sdk.utils.Options;


public class AsyncLivePlayback {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final LivePlayback syncSDK;

    AsyncLivePlayback(LivePlayback syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public LivePlayback sync() {
        return syncSDK;
    }


    /**
     * Create a playbackId
     * 
     * <p>Generates a new playback ID for the live stream, allowing viewers to access the stream through this
     * ID. The playback ID can be shared with viewers for direct access to the live broadcast.
     * 
     * <p>By calling this endpoint with the `streamId`, FastPix returns a unique `playbackId`, which can be
     * used to stream the live content.
     * 
     * <p>#### Example
     * 
     * <p>A media platform needs to distribute a unique playback ID to users for an exclusive live concert.
     * The platform can also embed the stream on various partner websites.
     * 
     * @return The async call builder
     */
    public CreatePlaybackIdOfStreamRequestBuilder createPlaybackId() {
        return new CreatePlaybackIdOfStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a playbackId
     * 
     * <p>Generates a new playback ID for the live stream, allowing viewers to access the stream through this
     * ID. The playback ID can be shared with viewers for direct access to the live broadcast.
     * 
     * <p>By calling this endpoint with the `streamId`, FastPix returns a unique `playbackId`, which can be
     * used to stream the live content.
     * 
     * <p>#### Example
     * 
     * <p>A media platform needs to distribute a unique playback ID to users for an exclusive live concert.
     * The platform can also embed the stream on various partner websites.
     * 
     * @param streamId After creating a new live stream, FastPix assigns a unique identifier to the stream.
     * @param body 
     * @return {@code CompletableFuture<CreatePlaybackIdOfStreamResponse>} - The async response
     */
    public CompletableFuture<CreatePlaybackIdOfStreamResponse> createPlaybackId(@Nonnull String streamId, @Nonnull PlaybackIdRequest body) {
        return createPlaybackId(streamId, body, null);
    }

    /**
     * Create a playbackId
     * 
     * <p>Generates a new playback ID for the live stream, allowing viewers to access the stream through this
     * ID. The playback ID can be shared with viewers for direct access to the live broadcast.
     * 
     * <p>By calling this endpoint with the `streamId`, FastPix returns a unique `playbackId`, which can be
     * used to stream the live content.
     * 
     * <p>#### Example
     * 
     * <p>A media platform needs to distribute a unique playback ID to users for an exclusive live concert.
     * The platform can also embed the stream on various partner websites.
     * 
     * @param streamId After creating a new live stream, FastPix assigns a unique identifier to the stream.
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<CreatePlaybackIdOfStreamResponse>} - The async response
     */
    public CompletableFuture<CreatePlaybackIdOfStreamResponse> createPlaybackId(
            @Nonnull String streamId, @Nonnull PlaybackIdRequest body,
            @Nullable Options options) {
        CreatePlaybackIdOfStreamRequest request = new CreatePlaybackIdOfStreamRequest(streamId, body);
        AsyncRequestOperation<CreatePlaybackIdOfStreamRequest, CreatePlaybackIdOfStreamResponse> operation
              = new CreatePlaybackIdOfStream.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete a playbackId
     * 
     * <p>Deletes a previously created playback ID for a live stream.This prevents new viewers from accessing
     * the stream using the playback ID, while current viewers can continue watching for a short period
     * before the connection ends. FastPix deletes the ID and ensures the new playback request fails.
     * 
     * <p>#### Example
     * A streaming service wants to prevent new users from joining a live stream that is nearing its end.
     * The host can delete the playback ID to ensure no one can join the stream or replay it once it ends.
     * 
     * @return The async call builder
     */
    public DeletePlaybackIdOfStreamRequestBuilder deletePlaybackId() {
        return new DeletePlaybackIdOfStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a playbackId
     * 
     * <p>Deletes a previously created playback ID for a live stream.This prevents new viewers from accessing
     * the stream using the playback ID, while current viewers can continue watching for a short period
     * before the connection ends. FastPix deletes the ID and ensures the new playback request fails.
     * 
     * <p>#### Example
     * A streaming service wants to prevent new users from joining a live stream that is nearing its end.
     * The host can delete the playback ID to ensure no one can join the stream or replay it once it ends.
     * 
     * @param streamId Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
     * @param playbackId Unique identifier for the playbackId
     * @return {@code CompletableFuture<DeletePlaybackIdOfStreamResponse>} - The async response
     */
    public CompletableFuture<DeletePlaybackIdOfStreamResponse> deletePlaybackId(@Nonnull String streamId, @Nonnull String playbackId) {
        return deletePlaybackId(streamId, playbackId, null);
    }

    /**
     * Delete a playbackId
     * 
     * <p>Deletes a previously created playback ID for a live stream.This prevents new viewers from accessing
     * the stream using the playback ID, while current viewers can continue watching for a short period
     * before the connection ends. FastPix deletes the ID and ensures the new playback request fails.
     * 
     * <p>#### Example
     * A streaming service wants to prevent new users from joining a live stream that is nearing its end.
     * The host can delete the playback ID to ensure no one can join the stream or replay it once it ends.
     * 
     * @param streamId Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
     * @param playbackId Unique identifier for the playbackId
     * @param options additional options
     * @return {@code CompletableFuture<DeletePlaybackIdOfStreamResponse>} - The async response
     */
    public CompletableFuture<DeletePlaybackIdOfStreamResponse> deletePlaybackId(
            @Nonnull String streamId, @Nonnull String playbackId,
            @Nullable Options options) {
        DeletePlaybackIdOfStreamRequest request = new DeletePlaybackIdOfStreamRequest(streamId, playbackId);
        AsyncRequestOperation<DeletePlaybackIdOfStreamRequest, DeletePlaybackIdOfStreamResponse> operation
              = new DeletePlaybackIdOfStream.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
