/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package io.fastpix.sdk;

import io.fastpix.sdk.utils.HasSecurity;

public interface SecuritySource {

    HasSecurity getSecurity();
    
    public static SecuritySource of(HasSecurity security) {
        return new DefaultSecuritySource(security);
    }

    public static class DefaultSecuritySource implements SecuritySource {
        private HasSecurity security;

        public DefaultSecuritySource(HasSecurity security) {
            this.security = security;
        }

        public HasSecurity getSecurity() {
            return security;
        }
    }
}
