/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.operations;

import io.fastpix.sdk.models.components.PlaybackIdRequest;
import io.fastpix.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class CreatePlaybackIdOfStreamRequestBuilder {

    private String streamId;
    private Optional<? extends PlaybackIdRequest> playbackIdRequest = Optional.empty();
    private final SDKMethodInterfaces.MethodCallCreatePlaybackIdOfStream sdk;

    public CreatePlaybackIdOfStreamRequestBuilder(SDKMethodInterfaces.MethodCallCreatePlaybackIdOfStream sdk) {
        this.sdk = sdk;
    }

    public CreatePlaybackIdOfStreamRequestBuilder streamId(String streamId) {
        Utils.checkNotNull(streamId, "streamId");
        this.streamId = streamId;
        return this;
    }
                
    public CreatePlaybackIdOfStreamRequestBuilder playbackIdRequest(PlaybackIdRequest playbackIdRequest) {
        Utils.checkNotNull(playbackIdRequest, "playbackIdRequest");
        this.playbackIdRequest = Optional.of(playbackIdRequest);
        return this;
    }

    public CreatePlaybackIdOfStreamRequestBuilder playbackIdRequest(Optional<? extends PlaybackIdRequest> playbackIdRequest) {
        Utils.checkNotNull(playbackIdRequest, "playbackIdRequest");
        this.playbackIdRequest = playbackIdRequest;
        return this;
    }

    public CreatePlaybackIdOfStreamResponse call() throws Exception {

        return sdk.createPlaybackIdOfStream(
            streamId,
            playbackIdRequest);
    }
}
