/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateMediaPlaybackIdDomainsDefaultPolicy
 * 
 * <p>Specifies the default access policy for domains. 
 * If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` list. 
 * If set to `deny`, all domains are denied access unless otherwise specified in the `allow` list.
 */
public enum CreateMediaPlaybackIdDomainsDefaultPolicy {
    ALLOW("allow"),
    DENY("deny");

    @JsonValue
    private final String value;

    private CreateMediaPlaybackIdDomainsDefaultPolicy(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateMediaPlaybackIdDomainsDefaultPolicy> fromValue(String value) {
        for (CreateMediaPlaybackIdDomainsDefaultPolicy o: CreateMediaPlaybackIdDomainsDefaultPolicy.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

