/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.fastpix.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.fastpix.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;

public class CreateMediaPlaybackIdAccessRestrictions {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("domains")
    private Optional<? extends CreateMediaPlaybackIdDomains> domains;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userAgents")
    private Optional<? extends CreateMediaPlaybackIdUserAgents> userAgents;

    @JsonCreator
    public CreateMediaPlaybackIdAccessRestrictions(
            @JsonProperty("domains") Optional<? extends CreateMediaPlaybackIdDomains> domains,
            @JsonProperty("userAgents") Optional<? extends CreateMediaPlaybackIdUserAgents> userAgents) {
        Utils.checkNotNull(domains, "domains");
        Utils.checkNotNull(userAgents, "userAgents");
        this.domains = domains;
        this.userAgents = userAgents;
    }
    
    public CreateMediaPlaybackIdAccessRestrictions() {
        this(Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CreateMediaPlaybackIdDomains> domains() {
        return (Optional<CreateMediaPlaybackIdDomains>) domains;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CreateMediaPlaybackIdUserAgents> userAgents() {
        return (Optional<CreateMediaPlaybackIdUserAgents>) userAgents;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public CreateMediaPlaybackIdAccessRestrictions withDomains(CreateMediaPlaybackIdDomains domains) {
        Utils.checkNotNull(domains, "domains");
        this.domains = Optional.ofNullable(domains);
        return this;
    }

    public CreateMediaPlaybackIdAccessRestrictions withDomains(Optional<? extends CreateMediaPlaybackIdDomains> domains) {
        Utils.checkNotNull(domains, "domains");
        this.domains = domains;
        return this;
    }

    public CreateMediaPlaybackIdAccessRestrictions withUserAgents(CreateMediaPlaybackIdUserAgents userAgents) {
        Utils.checkNotNull(userAgents, "userAgents");
        this.userAgents = Optional.ofNullable(userAgents);
        return this;
    }

    public CreateMediaPlaybackIdAccessRestrictions withUserAgents(Optional<? extends CreateMediaPlaybackIdUserAgents> userAgents) {
        Utils.checkNotNull(userAgents, "userAgents");
        this.userAgents = userAgents;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateMediaPlaybackIdAccessRestrictions other = (CreateMediaPlaybackIdAccessRestrictions) o;
        return 
            Objects.deepEquals(this.domains, other.domains) &&
            Objects.deepEquals(this.userAgents, other.userAgents);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            domains,
            userAgents);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateMediaPlaybackIdAccessRestrictions.class,
                "domains", domains,
                "userAgents", userAgents);
    }
    
    public final static class Builder {
 
        private Optional<? extends CreateMediaPlaybackIdDomains> domains = Optional.empty();
 
        private Optional<? extends CreateMediaPlaybackIdUserAgents> userAgents = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder domains(CreateMediaPlaybackIdDomains domains) {
            Utils.checkNotNull(domains, "domains");
            this.domains = Optional.ofNullable(domains);
            return this;
        }

        public Builder domains(Optional<? extends CreateMediaPlaybackIdDomains> domains) {
            Utils.checkNotNull(domains, "domains");
            this.domains = domains;
            return this;
        }

        public Builder userAgents(CreateMediaPlaybackIdUserAgents userAgents) {
            Utils.checkNotNull(userAgents, "userAgents");
            this.userAgents = Optional.ofNullable(userAgents);
            return this;
        }

        public Builder userAgents(Optional<? extends CreateMediaPlaybackIdUserAgents> userAgents) {
            Utils.checkNotNull(userAgents, "userAgents");
            this.userAgents = userAgents;
            return this;
        }
        
        public CreateMediaPlaybackIdAccessRestrictions build() {
            return new CreateMediaPlaybackIdAccessRestrictions(
                domains,
                userAgents);
        }
    }
}
