/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package io.fastpix.sdk.models.operations;

import static io.fastpix.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import io.fastpix.sdk.SDKConfiguration;
import io.fastpix.sdk.operations.GetSpecificSimulcastOfStream;
import io.fastpix.sdk.utils.Headers;
import io.fastpix.sdk.utils.Options;
import io.fastpix.sdk.utils.RetryConfig;
import io.fastpix.sdk.utils.Utils;

public class GetSpecificSimulcastOfStreamRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetSpecificSimulcastOfStreamRequest.Builder pojoBuilder;
    private GetSpecificSimulcastOfStreamRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public GetSpecificSimulcastOfStreamRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetSpecificSimulcastOfStreamRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public GetSpecificSimulcastOfStreamRequestBuilder streamId(@Nonnull String streamId) {
        this.pojoBuilder.streamId(streamId);
        this._setterCalled = true;
        return this;
    }

    public GetSpecificSimulcastOfStreamRequestBuilder simulcastId(@Nonnull String simulcastId) {
        this.pojoBuilder.simulcastId(simulcastId);
        this._setterCalled = true;
        return this;
    }

    public GetSpecificSimulcastOfStreamRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private GetSpecificSimulcastOfStreamRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetSpecificSimulcastOfStreamRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetSpecificSimulcastOfStreamResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<GetSpecificSimulcastOfStreamRequest, GetSpecificSimulcastOfStreamResponse> operation
              = new GetSpecificSimulcastOfStream.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
