/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package io.fastpix.sdk.models.operations;

import static io.fastpix.sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import io.fastpix.sdk.SDKConfiguration;
import io.fastpix.sdk.operations.UpdateMediaSummary;
import io.fastpix.sdk.utils.Headers;
import io.fastpix.sdk.utils.Options;
import io.fastpix.sdk.utils.RetryConfig;
import io.fastpix.sdk.utils.Utils;

public class UpdateMediaSummaryRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final UpdateMediaSummaryRequest.Builder pojoBuilder;
    private UpdateMediaSummaryRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public UpdateMediaSummaryRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = UpdateMediaSummaryRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public UpdateMediaSummaryRequestBuilder mediaId(@Nonnull String mediaId) {
        this.pojoBuilder.mediaId(mediaId);
        this._setterCalled = true;
        return this;
    }

    public UpdateMediaSummaryRequestBuilder body(@Nonnull UpdateMediaSummaryRequestBody body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public UpdateMediaSummaryRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private UpdateMediaSummaryRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public UpdateMediaSummaryRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public UpdateMediaSummaryResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<UpdateMediaSummaryRequest, UpdateMediaSummaryResponse> operation
              = new UpdateMediaSummary.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
