/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class CreateMediaRequestAccessRestrictions {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("domains")
    private CreateMediaRequestDomains domains;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userAgents")
    private CreateMediaRequestUserAgents userAgents;

    @JsonCreator
    public CreateMediaRequestAccessRestrictions(
            @JsonProperty("domains") @Nullable CreateMediaRequestDomains domains,
            @JsonProperty("userAgents") @Nullable CreateMediaRequestUserAgents userAgents) {
        this.domains = domains;
        this.userAgents = userAgents;
    }
    
    public CreateMediaRequestAccessRestrictions() {
        this(null, null);
    }

    public Optional<CreateMediaRequestDomains> domains() {
        return Optional.ofNullable(this.domains);
    }

    public Optional<CreateMediaRequestUserAgents> userAgents() {
        return Optional.ofNullable(this.userAgents);
    }

    public static Builder builder() {
        return new Builder();
    }


    public CreateMediaRequestAccessRestrictions withDomains(@Nullable CreateMediaRequestDomains domains) {
        this.domains = domains;
        return this;
    }


    public CreateMediaRequestAccessRestrictions withUserAgents(@Nullable CreateMediaRequestUserAgents userAgents) {
        this.userAgents = userAgents;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateMediaRequestAccessRestrictions other = (CreateMediaRequestAccessRestrictions) o;
        return 
            Utils.enhancedDeepEquals(this.domains, other.domains) &&
            Utils.enhancedDeepEquals(this.userAgents, other.userAgents);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            domains, userAgents);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateMediaRequestAccessRestrictions.class,
                "domains", domains,
                "userAgents", userAgents);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private CreateMediaRequestDomains domains;

        private CreateMediaRequestUserAgents userAgents;

        private Builder() {
          // force use of static builder() method
        }

        public Builder domains(@Nullable CreateMediaRequestDomains domains) {
            this.domains = domains;
            return this;
        }

        public Builder userAgents(@Nullable CreateMediaRequestUserAgents userAgents) {
            this.userAgents = userAgents;
            return this;
        }

        public CreateMediaRequestAccessRestrictions build() {
            return new CreateMediaRequestAccessRestrictions(
                domains, userAgents);
        }

    }
}
