/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class CreateMediaRequestDomains {
    /**
     * Specifies the default access policy for domains.
     * If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` lists.
     * If set to `deny`, all domains are denied access unless otherwise specified in the `allow` lists.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("defaultPolicy")
    private DomainsDefaultPolicy defaultPolicy;

    /**
     * A list of domain names or patterns that are explicitly allowed access.
     * This list is only effective when the `defaultPolicy` is set to `deny`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("allow")
    private List<String> allow;

    /**
     * A list of domain names or patterns that are explicitly denied access.
     * This list is only effective when the `defaultPolicy` is set to `allow`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deny")
    private List<String> deny;

    @JsonCreator
    public CreateMediaRequestDomains(
            @JsonProperty("defaultPolicy") @Nullable DomainsDefaultPolicy defaultPolicy,
            @JsonProperty("allow") @Nullable List<String> allow,
            @JsonProperty("deny") @Nullable List<String> deny) {
        this.defaultPolicy = defaultPolicy;
        this.allow = allow;
        this.deny = deny;
    }
    
    public CreateMediaRequestDomains() {
        this(null, null, null);
    }

    /**
     * Specifies the default access policy for domains.
     * If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` lists.
     * If set to `deny`, all domains are denied access unless otherwise specified in the `allow` lists.
     */
    public Optional<DomainsDefaultPolicy> defaultPolicy() {
        return Optional.ofNullable(this.defaultPolicy);
    }

    /**
     * A list of domain names or patterns that are explicitly allowed access.
     * This list is only effective when the `defaultPolicy` is set to `deny`.
     */
    public Optional<List<String>> allow() {
        return Optional.ofNullable(this.allow);
    }

    /**
     * A list of domain names or patterns that are explicitly denied access.
     * This list is only effective when the `defaultPolicy` is set to `allow`.
     */
    public Optional<List<String>> deny() {
        return Optional.ofNullable(this.deny);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Specifies the default access policy for domains.
     * If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` lists.
     * If set to `deny`, all domains are denied access unless otherwise specified in the `allow` lists.
     */
    public CreateMediaRequestDomains withDefaultPolicy(@Nullable DomainsDefaultPolicy defaultPolicy) {
        this.defaultPolicy = defaultPolicy;
        return this;
    }


    /**
     * A list of domain names or patterns that are explicitly allowed access.
     * This list is only effective when the `defaultPolicy` is set to `deny`.
     */
    public CreateMediaRequestDomains withAllow(@Nullable List<String> allow) {
        this.allow = allow;
        return this;
    }


    /**
     * A list of domain names or patterns that are explicitly denied access.
     * This list is only effective when the `defaultPolicy` is set to `allow`.
     */
    public CreateMediaRequestDomains withDeny(@Nullable List<String> deny) {
        this.deny = deny;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateMediaRequestDomains other = (CreateMediaRequestDomains) o;
        return 
            Utils.enhancedDeepEquals(this.defaultPolicy, other.defaultPolicy) &&
            Utils.enhancedDeepEquals(this.allow, other.allow) &&
            Utils.enhancedDeepEquals(this.deny, other.deny);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            defaultPolicy, allow, deny);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateMediaRequestDomains.class,
                "defaultPolicy", defaultPolicy,
                "allow", allow,
                "deny", deny);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private DomainsDefaultPolicy defaultPolicy;

        private List<String> allow;

        private List<String> deny;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Specifies the default access policy for domains.
         * If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` lists.
         * If set to `deny`, all domains are denied access unless otherwise specified in the `allow` lists.
         */
        public Builder defaultPolicy(@Nullable DomainsDefaultPolicy defaultPolicy) {
            this.defaultPolicy = defaultPolicy;
            return this;
        }

        /**
         * A list of domain names or patterns that are explicitly allowed access.
         * This list is only effective when the `defaultPolicy` is set to `deny`.
         */
        public Builder allow(@Nullable List<String> allow) {
            this.allow = allow;
            return this;
        }

        /**
         * A list of domain names or patterns that are explicitly denied access.
         * This list is only effective when the `defaultPolicy` is set to `allow`.
         */
        public Builder deny(@Nullable List<String> deny) {
            this.deny = deny;
            return this;
        }

        public CreateMediaRequestDomains build() {
            return new CreateMediaRequestDomains(
                defaultPolicy, allow, deny);
        }

    }
}
