/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateLiveStreamRequestMaxResolution
 * 
 * <p>Defines the maximum resolution for encoding, storage, and playback of the live stream.
 */
public enum CreateLiveStreamRequestMaxResolution {
    ONE_THOUSAND_AND_EIGHTYP("1080p"),
    SEVEN_HUNDRED_AND_TWENTYP("720p"),
    FOUR_HUNDRED_AND_EIGHTYP("480p");

    @JsonValue
    private final String value;

    CreateLiveStreamRequestMaxResolution(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateLiveStreamRequestMaxResolution> fromValue(String value) {
        for (CreateLiveStreamRequestMaxResolution o: CreateLiveStreamRequestMaxResolution.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

