/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * Custom2
 * 
 * <p>User defined metadata. Only accessible once it is enabled in the organization settings.
 */
public class Custom2 {
    /**
     * A list of custom dimension objects.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("Custom")
    private List<Custom1> custom;

    @JsonCreator
    public Custom2(
            @JsonProperty("Custom") @Nullable List<Custom1> custom) {
        this.custom = custom;
    }
    
    public Custom2() {
        this(null);
    }

    /**
     * A list of custom dimension objects.
     */
    public Optional<List<Custom1>> custom() {
        return Optional.ofNullable(this.custom);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A list of custom dimension objects.
     */
    public Custom2 withCustom(@Nullable List<Custom1> custom) {
        this.custom = custom;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Custom2 other = (Custom2) o;
        return 
            Utils.enhancedDeepEquals(this.custom, other.custom);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            custom);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Custom2.class,
                "custom", custom);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<Custom1> custom;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A list of custom dimension objects.
         */
        public Builder custom(@Nullable List<Custom1> custom) {
            this.custom = custom;
            return this;
        }

        public Custom2 build() {
            return new Custom2(
                custom);
        }

    }
}
