/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * DirectUploadStatus
 * 
 * <p>Determines the media's status, which can be one of the possible values.
 */
public class DirectUploadStatus {

    public static final DirectUploadStatus WAITING = new DirectUploadStatus("waiting");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DirectUploadStatus> values = createValuesMap();
    private static final Map<String, DirectUploadStatusEnum> enums = createEnumsMap();

    private final String value;

    private DirectUploadStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a DirectUploadStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DirectUploadStatus
     */ 
    @JsonCreator
    public static DirectUploadStatus of(String value) {
        synchronized (DirectUploadStatus.class) {
            return values.computeIfAbsent(value, v -> new DirectUploadStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DirectUploadStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DirectUploadStatus other = (DirectUploadStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DirectUploadStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static DirectUploadStatus[] values() {
        synchronized (DirectUploadStatus.class) {
            return values.values().toArray(new DirectUploadStatus[] {});
        }
    }

    private static final Map<String, DirectUploadStatus> createValuesMap() {
        Map<String, DirectUploadStatus> map = new LinkedHashMap<>();
        map.put("waiting", WAITING);
        return map;
    }

    private static final Map<String, DirectUploadStatusEnum> createEnumsMap() {
        Map<String, DirectUploadStatusEnum> map = new HashMap<>();
        map.put("waiting", DirectUploadStatusEnum.WAITING);
        return map;
    }
    
    
    public enum DirectUploadStatusEnum {

        WAITING("waiting"),;

        private final String value;

        private DirectUploadStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

