/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * DomainsDefaultPolicy
 * 
 * <p>Specifies the default access policy for domains.
 * If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` lists.
 * If set to `deny`, all domains are denied access unless otherwise specified in the `allow` lists.
 */
public enum DomainsDefaultPolicy {
    ALLOW("allow"),
    DENY("deny");

    @JsonValue
    private final String value;

    DomainsDefaultPolicy(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<DomainsDefaultPolicy> fromValue(String value) {
        for (DomainsDefaultPolicy o: DomainsDefaultPolicy.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

