/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * GetAllSigningKeysResponseDto
 * 
 * <p>Displays the result of the request.
 */
public class GetAllSigningKeysResponseDto {
    /**
     * A unique identifier is generated by FastPix for the signing keys.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    /**
     * Time the Signing key was generated, defined as a localDateTime (UTC Time).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("createdAt")
    private OffsetDateTime createdAt;

    @JsonCreator
    public GetAllSigningKeysResponseDto(
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("createdAt") @Nullable OffsetDateTime createdAt) {
        this.id = id;
        this.createdAt = createdAt;
    }
    
    public GetAllSigningKeysResponseDto() {
        this(null, null);
    }

    /**
     * A unique identifier is generated by FastPix for the signing keys.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * Time the Signing key was generated, defined as a localDateTime (UTC Time).
     */
    public Optional<OffsetDateTime> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A unique identifier is generated by FastPix for the signing keys.
     */
    public GetAllSigningKeysResponseDto withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    /**
     * Time the Signing key was generated, defined as a localDateTime (UTC Time).
     */
    public GetAllSigningKeysResponseDto withCreatedAt(@Nullable OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAllSigningKeysResponseDto other = (GetAllSigningKeysResponseDto) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, createdAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAllSigningKeysResponseDto.class,
                "id", id,
                "createdAt", createdAt);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private OffsetDateTime createdAt;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A unique identifier is generated by FastPix for the signing keys.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /**
         * Time the Signing key was generated, defined as a localDateTime (UTC Time).
         */
        public Builder createdAt(@Nullable OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public GetAllSigningKeysResponseDto build() {
            return new GetAllSigningKeysResponseDto(
                id, createdAt);
        }

    }
}
