/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetAllMediaResponseMp4Support
 * 
 * <p>Determines the type of MP4 support for the media.
 * - **none**: Disables MP4 support.
 * - **capped_4k**: Enables MP4 downloads with resolutions up to 4K.
 * - **audioOnly**: Provides an MP4 stream containing only the audio.
 * - **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.
 */
public class GetAllMediaResponseMp4Support {

    public static final GetAllMediaResponseMp4Support NONE = new GetAllMediaResponseMp4Support("none");
    public static final GetAllMediaResponseMp4Support CAPPED4K = new GetAllMediaResponseMp4Support("capped_4k");
    public static final GetAllMediaResponseMp4Support AUDIO_ONLY = new GetAllMediaResponseMp4Support("audioOnly");
    public static final GetAllMediaResponseMp4Support AUDIO_ONLY_CAPPED4K = new GetAllMediaResponseMp4Support("audioOnly,capped_4k");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetAllMediaResponseMp4Support> values = createValuesMap();
    private static final Map<String, GetAllMediaResponseMp4SupportEnum> enums = createEnumsMap();

    private final String value;

    private GetAllMediaResponseMp4Support(String value) {
        this.value = value;
    }

    /**
     * Returns a GetAllMediaResponseMp4Support with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetAllMediaResponseMp4Support
     */ 
    @JsonCreator
    public static GetAllMediaResponseMp4Support of(String value) {
        synchronized (GetAllMediaResponseMp4Support.class) {
            return values.computeIfAbsent(value, v -> new GetAllMediaResponseMp4Support(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetAllMediaResponseMp4SupportEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetAllMediaResponseMp4Support other = (GetAllMediaResponseMp4Support) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetAllMediaResponseMp4Support [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetAllMediaResponseMp4Support[] values() {
        synchronized (GetAllMediaResponseMp4Support.class) {
            return values.values().toArray(new GetAllMediaResponseMp4Support[] {});
        }
    }

    private static final Map<String, GetAllMediaResponseMp4Support> createValuesMap() {
        Map<String, GetAllMediaResponseMp4Support> map = new LinkedHashMap<>();
        map.put("none", NONE);
        map.put("capped_4k", CAPPED4K);
        map.put("audioOnly", AUDIO_ONLY);
        map.put("audioOnly,capped_4k", AUDIO_ONLY_CAPPED4K);
        return map;
    }

    private static final Map<String, GetAllMediaResponseMp4SupportEnum> createEnumsMap() {
        Map<String, GetAllMediaResponseMp4SupportEnum> map = new HashMap<>();
        map.put("none", GetAllMediaResponseMp4SupportEnum.NONE);
        map.put("capped_4k", GetAllMediaResponseMp4SupportEnum.CAPPED4K);
        map.put("audioOnly", GetAllMediaResponseMp4SupportEnum.AUDIO_ONLY);
        map.put("audioOnly,capped_4k", GetAllMediaResponseMp4SupportEnum.AUDIO_ONLY_CAPPED4K);
        return map;
    }
    
    
    public enum GetAllMediaResponseMp4SupportEnum {

        NONE("none"),
        CAPPED4K("capped_4k"),
        AUDIO_ONLY("audioOnly"),
        AUDIO_ONLY_CAPPED4K("audioOnly,capped_4k"),;

        private final String value;

        private GetAllMediaResponseMp4SupportEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

