/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetAllMediaResponseMaxResolution
 * 
 * <p>The maximum resolution specified by the user for the media.
 */
public class GetAllMediaResponseMaxResolution {

    public static final GetAllMediaResponseMaxResolution TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP = new GetAllMediaResponseMaxResolution("2160p");
    public static final GetAllMediaResponseMaxResolution ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP = new GetAllMediaResponseMaxResolution("1440p");
    public static final GetAllMediaResponseMaxResolution ONE_THOUSAND_AND_EIGHTYP = new GetAllMediaResponseMaxResolution("1080p");
    public static final GetAllMediaResponseMaxResolution SEVEN_HUNDRED_AND_TWENTYP = new GetAllMediaResponseMaxResolution("720p");
    public static final GetAllMediaResponseMaxResolution FOUR_HUNDRED_AND_EIGHTYP = new GetAllMediaResponseMaxResolution("480p");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetAllMediaResponseMaxResolution> values = createValuesMap();
    private static final Map<String, GetAllMediaResponseMaxResolutionEnum> enums = createEnumsMap();

    private final String value;

    private GetAllMediaResponseMaxResolution(String value) {
        this.value = value;
    }

    /**
     * Returns a GetAllMediaResponseMaxResolution with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetAllMediaResponseMaxResolution
     */ 
    @JsonCreator
    public static GetAllMediaResponseMaxResolution of(String value) {
        synchronized (GetAllMediaResponseMaxResolution.class) {
            return values.computeIfAbsent(value, v -> new GetAllMediaResponseMaxResolution(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetAllMediaResponseMaxResolutionEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetAllMediaResponseMaxResolution other = (GetAllMediaResponseMaxResolution) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetAllMediaResponseMaxResolution [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetAllMediaResponseMaxResolution[] values() {
        synchronized (GetAllMediaResponseMaxResolution.class) {
            return values.values().toArray(new GetAllMediaResponseMaxResolution[] {});
        }
    }

    private static final Map<String, GetAllMediaResponseMaxResolution> createValuesMap() {
        Map<String, GetAllMediaResponseMaxResolution> map = new LinkedHashMap<>();
        map.put("2160p", TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP);
        map.put("1440p", ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP);
        map.put("1080p", ONE_THOUSAND_AND_EIGHTYP);
        map.put("720p", SEVEN_HUNDRED_AND_TWENTYP);
        map.put("480p", FOUR_HUNDRED_AND_EIGHTYP);
        return map;
    }

    private static final Map<String, GetAllMediaResponseMaxResolutionEnum> createEnumsMap() {
        Map<String, GetAllMediaResponseMaxResolutionEnum> map = new HashMap<>();
        map.put("2160p", GetAllMediaResponseMaxResolutionEnum.TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP);
        map.put("1440p", GetAllMediaResponseMaxResolutionEnum.ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP);
        map.put("1080p", GetAllMediaResponseMaxResolutionEnum.ONE_THOUSAND_AND_EIGHTYP);
        map.put("720p", GetAllMediaResponseMaxResolutionEnum.SEVEN_HUNDRED_AND_TWENTYP);
        map.put("480p", GetAllMediaResponseMaxResolutionEnum.FOUR_HUNDRED_AND_EIGHTYP);
        return map;
    }
    
    
    public enum GetAllMediaResponseMaxResolutionEnum {

        TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP("2160p"),
        ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP("1440p"),
        ONE_THOUSAND_AND_EIGHTYP("1080p"),
        SEVEN_HUNDRED_AND_TWENTYP("720p"),
        FOUR_HUNDRED_AND_EIGHTYP("480p"),;

        private final String value;

        private GetAllMediaResponseMaxResolutionEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

