/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetAllMediaResponseMediaQuality
 * 
 * <p>The quality tier applied to the media.
 */
public class GetAllMediaResponseMediaQuality {

    public static final GetAllMediaResponseMediaQuality STANDARD = new GetAllMediaResponseMediaQuality("standard");
    public static final GetAllMediaResponseMediaQuality PRO = new GetAllMediaResponseMediaQuality("pro");
    public static final GetAllMediaResponseMediaQuality PREMIUM = new GetAllMediaResponseMediaQuality("premium");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetAllMediaResponseMediaQuality> values = createValuesMap();
    private static final Map<String, GetAllMediaResponseMediaQualityEnum> enums = createEnumsMap();

    private final String value;

    private GetAllMediaResponseMediaQuality(String value) {
        this.value = value;
    }

    /**
     * Returns a GetAllMediaResponseMediaQuality with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetAllMediaResponseMediaQuality
     */ 
    @JsonCreator
    public static GetAllMediaResponseMediaQuality of(String value) {
        synchronized (GetAllMediaResponseMediaQuality.class) {
            return values.computeIfAbsent(value, v -> new GetAllMediaResponseMediaQuality(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetAllMediaResponseMediaQualityEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetAllMediaResponseMediaQuality other = (GetAllMediaResponseMediaQuality) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetAllMediaResponseMediaQuality [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetAllMediaResponseMediaQuality[] values() {
        synchronized (GetAllMediaResponseMediaQuality.class) {
            return values.values().toArray(new GetAllMediaResponseMediaQuality[] {});
        }
    }

    private static final Map<String, GetAllMediaResponseMediaQuality> createValuesMap() {
        Map<String, GetAllMediaResponseMediaQuality> map = new LinkedHashMap<>();
        map.put("standard", STANDARD);
        map.put("pro", PRO);
        map.put("premium", PREMIUM);
        return map;
    }

    private static final Map<String, GetAllMediaResponseMediaQualityEnum> createEnumsMap() {
        Map<String, GetAllMediaResponseMediaQualityEnum> map = new HashMap<>();
        map.put("standard", GetAllMediaResponseMediaQualityEnum.STANDARD);
        map.put("pro", GetAllMediaResponseMediaQualityEnum.PRO);
        map.put("premium", GetAllMediaResponseMediaQualityEnum.PREMIUM);
        return map;
    }
    
    
    public enum GetAllMediaResponseMediaQualityEnum {

        STANDARD("standard"),
        PRO("pro"),
        PREMIUM("premium"),;

        private final String value;

        private GetAllMediaResponseMediaQualityEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

