/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetMediaResponseMaxResolution
 * 
 * <p>The maximum resolution specified by the user for the media.
 */
public class GetMediaResponseMaxResolution {

    public static final GetMediaResponseMaxResolution TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP = new GetMediaResponseMaxResolution("2160p");
    public static final GetMediaResponseMaxResolution ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP = new GetMediaResponseMaxResolution("1440p");
    public static final GetMediaResponseMaxResolution ONE_THOUSAND_AND_EIGHTYP = new GetMediaResponseMaxResolution("1080p");
    public static final GetMediaResponseMaxResolution SEVEN_HUNDRED_AND_TWENTYP = new GetMediaResponseMaxResolution("720p");
    public static final GetMediaResponseMaxResolution FOUR_HUNDRED_AND_EIGHTYP = new GetMediaResponseMaxResolution("480p");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetMediaResponseMaxResolution> values = createValuesMap();
    private static final Map<String, GetMediaResponseMaxResolutionEnum> enums = createEnumsMap();

    private final String value;

    private GetMediaResponseMaxResolution(String value) {
        this.value = value;
    }

    /**
     * Returns a GetMediaResponseMaxResolution with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetMediaResponseMaxResolution
     */ 
    @JsonCreator
    public static GetMediaResponseMaxResolution of(String value) {
        synchronized (GetMediaResponseMaxResolution.class) {
            return values.computeIfAbsent(value, v -> new GetMediaResponseMaxResolution(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetMediaResponseMaxResolutionEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetMediaResponseMaxResolution other = (GetMediaResponseMaxResolution) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetMediaResponseMaxResolution [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetMediaResponseMaxResolution[] values() {
        synchronized (GetMediaResponseMaxResolution.class) {
            return values.values().toArray(new GetMediaResponseMaxResolution[] {});
        }
    }

    private static final Map<String, GetMediaResponseMaxResolution> createValuesMap() {
        Map<String, GetMediaResponseMaxResolution> map = new LinkedHashMap<>();
        map.put("2160p", TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP);
        map.put("1440p", ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP);
        map.put("1080p", ONE_THOUSAND_AND_EIGHTYP);
        map.put("720p", SEVEN_HUNDRED_AND_TWENTYP);
        map.put("480p", FOUR_HUNDRED_AND_EIGHTYP);
        return map;
    }

    private static final Map<String, GetMediaResponseMaxResolutionEnum> createEnumsMap() {
        Map<String, GetMediaResponseMaxResolutionEnum> map = new HashMap<>();
        map.put("2160p", GetMediaResponseMaxResolutionEnum.TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP);
        map.put("1440p", GetMediaResponseMaxResolutionEnum.ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP);
        map.put("1080p", GetMediaResponseMaxResolutionEnum.ONE_THOUSAND_AND_EIGHTYP);
        map.put("720p", GetMediaResponseMaxResolutionEnum.SEVEN_HUNDRED_AND_TWENTYP);
        map.put("480p", GetMediaResponseMaxResolutionEnum.FOUR_HUNDRED_AND_EIGHTYP);
        return map;
    }
    
    
    public enum GetMediaResponseMaxResolutionEnum {

        TWO_THOUSAND_ONE_HUNDRED_AND_SIXTYP("2160p"),
        ONE_THOUSAND_FOUR_HUNDRED_AND_FORTYP("1440p"),
        ONE_THOUSAND_AND_EIGHTYP("1080p"),
        SEVEN_HUNDRED_AND_TWENTYP("720p"),
        FOUR_HUNDRED_AND_EIGHTYP("480p"),;

        private final String value;

        private GetMediaResponseMaxResolutionEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

