/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * GetStreamsResponse
 * 
 * <p>Displays the result of the request.
 */
public class GetStreamsResponse {
    /**
     * Shows the request status. Returns true for success and false for failure.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("success")
    private Boolean success;

    /**
     * Displays the result of the request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private List<GetCreateLiveStreamResponseDTO> data;

    /**
     * Pagination organizes content into pages for better readability and navigation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pagination")
    private LiveStreamPagination pagination;

    @JsonCreator
    public GetStreamsResponse(
            @JsonProperty("success") @Nullable Boolean success,
            @JsonProperty("data") @Nullable List<GetCreateLiveStreamResponseDTO> data,
            @JsonProperty("pagination") @Nullable LiveStreamPagination pagination) {
        this.success = success;
        this.data = data;
        this.pagination = pagination;
    }
    
    public GetStreamsResponse() {
        this(null, null, null);
    }

    /**
     * Shows the request status. Returns true for success and false for failure.
     */
    public Optional<Boolean> success() {
        return Optional.ofNullable(this.success);
    }

    /**
     * Displays the result of the request.
     */
    public Optional<List<GetCreateLiveStreamResponseDTO>> data() {
        return Optional.ofNullable(this.data);
    }

    /**
     * Pagination organizes content into pages for better readability and navigation.
     */
    public Optional<LiveStreamPagination> pagination() {
        return Optional.ofNullable(this.pagination);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Shows the request status. Returns true for success and false for failure.
     */
    public GetStreamsResponse withSuccess(@Nullable Boolean success) {
        this.success = success;
        return this;
    }


    /**
     * Displays the result of the request.
     */
    public GetStreamsResponse withData(@Nullable List<GetCreateLiveStreamResponseDTO> data) {
        this.data = data;
        return this;
    }


    /**
     * Pagination organizes content into pages for better readability and navigation.
     */
    public GetStreamsResponse withPagination(@Nullable LiveStreamPagination pagination) {
        this.pagination = pagination;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetStreamsResponse other = (GetStreamsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.success, other.success) &&
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.pagination, other.pagination);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            success, data, pagination);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetStreamsResponse.class,
                "success", success,
                "data", data,
                "pagination", pagination);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Boolean success;

        private List<GetCreateLiveStreamResponseDTO> data;

        private LiveStreamPagination pagination;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Shows the request status. Returns true for success and false for failure.
         */
        public Builder success(@Nullable Boolean success) {
            this.success = success;
            return this;
        }

        /**
         * Displays the result of the request.
         */
        public Builder data(@Nullable List<GetCreateLiveStreamResponseDTO> data) {
            this.data = data;
            return this;
        }

        /**
         * Pagination organizes content into pages for better readability and navigation.
         */
        public Builder pagination(@Nullable LiveStreamPagination pagination) {
            this.pagination = pagination;
            return this;
        }

        public GetStreamsResponse build() {
            return new GetStreamsResponse(
                success, data, pagination);
        }

    }
}
