/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class Placement {
    /**
     * Horizontal alignment of the watermark.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("xAlign")
    private XAlign xAlign;

    /**
     * Horizontal margin from the edge of the video.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("xMargin")
    private String xMargin;

    /**
     * Vertical alignment of the watermark.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("yAlign")
    private YAlign yAlign;

    /**
     * Vertical margin from the edge of the video.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("yMargin")
    private String yMargin;

    @JsonCreator
    public Placement(
            @JsonProperty("xAlign") @Nullable XAlign xAlign,
            @JsonProperty("xMargin") @Nullable String xMargin,
            @JsonProperty("yAlign") @Nullable YAlign yAlign,
            @JsonProperty("yMargin") @Nullable String yMargin) {
        this.xAlign = xAlign;
        this.xMargin = xMargin;
        this.yAlign = yAlign;
        this.yMargin = yMargin;
    }
    
    public Placement() {
        this(null, null, null,
            null);
    }

    /**
     * Horizontal alignment of the watermark.
     */
    public Optional<XAlign> xAlign() {
        return Optional.ofNullable(this.xAlign);
    }

    /**
     * Horizontal margin from the edge of the video.
     */
    public Optional<String> xMargin() {
        return Optional.ofNullable(this.xMargin);
    }

    /**
     * Vertical alignment of the watermark.
     */
    public Optional<YAlign> yAlign() {
        return Optional.ofNullable(this.yAlign);
    }

    /**
     * Vertical margin from the edge of the video.
     */
    public Optional<String> yMargin() {
        return Optional.ofNullable(this.yMargin);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Horizontal alignment of the watermark.
     */
    public Placement withXAlign(@Nullable XAlign xAlign) {
        this.xAlign = xAlign;
        return this;
    }


    /**
     * Horizontal margin from the edge of the video.
     */
    public Placement withXMargin(@Nullable String xMargin) {
        this.xMargin = xMargin;
        return this;
    }


    /**
     * Vertical alignment of the watermark.
     */
    public Placement withYAlign(@Nullable YAlign yAlign) {
        this.yAlign = yAlign;
        return this;
    }


    /**
     * Vertical margin from the edge of the video.
     */
    public Placement withYMargin(@Nullable String yMargin) {
        this.yMargin = yMargin;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Placement other = (Placement) o;
        return 
            Utils.enhancedDeepEquals(this.xAlign, other.xAlign) &&
            Utils.enhancedDeepEquals(this.xMargin, other.xMargin) &&
            Utils.enhancedDeepEquals(this.yAlign, other.yAlign) &&
            Utils.enhancedDeepEquals(this.yMargin, other.yMargin);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            xAlign, xMargin, yAlign,
            yMargin);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Placement.class,
                "xAlign", xAlign,
                "xMargin", xMargin,
                "yAlign", yAlign,
                "yMargin", yMargin);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private XAlign xAlign;

        private String xMargin;

        private YAlign yAlign;

        private String yMargin;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Horizontal alignment of the watermark.
         */
        public Builder xAlign(@Nullable XAlign xAlign) {
            this.xAlign = xAlign;
            return this;
        }

        /**
         * Horizontal margin from the edge of the video.
         */
        public Builder xMargin(@Nullable String xMargin) {
            this.xMargin = xMargin;
            return this;
        }

        /**
         * Vertical alignment of the watermark.
         */
        public Builder yAlign(@Nullable YAlign yAlign) {
            this.yAlign = yAlign;
            return this;
        }

        /**
         * Vertical margin from the edge of the video.
         */
        public Builder yMargin(@Nullable String yMargin) {
            this.yMargin = yMargin;
            return this;
        }

        public Placement build() {
            return new Placement(
                xAlign, xMargin, yAlign,
                yMargin);
        }

    }
}
