/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class PullVideoInputSegment1 {
    /**
     * The URL of the **video segment** to be added.
     * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve and
     * process the segment successfully.
     * Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and performance.
     */
    @JsonProperty("url")
    private String url;

    /**
     * The timestamp(in seconds) at which the segment must be inserted.
     */
    @JsonProperty("insertAt")
    private long insertAt;

    @JsonCreator
    public PullVideoInputSegment1(
            @JsonProperty("url") @Nonnull String url,
            @JsonProperty("insertAt") long insertAt) {
        this.url = Optional.ofNullable(url)
            .orElseThrow(() -> new IllegalArgumentException("url cannot be null"));
        this.insertAt = insertAt;
    }

    /**
     * The URL of the **video segment** to be added.
     * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve and
     * process the segment successfully.
     * Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and performance.
     */
    public String url() {
        return this.url;
    }

    /**
     * The timestamp(in seconds) at which the segment must be inserted.
     */
    public long insertAt() {
        return this.insertAt;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The URL of the **video segment** to be added.
     * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve and
     * process the segment successfully.
     * Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and performance.
     */
    public PullVideoInputSegment1 withUrl(@Nonnull String url) {
        this.url = Utils.checkNotNull(url, "url");
        return this;
    }


    /**
     * The timestamp(in seconds) at which the segment must be inserted.
     */
    public PullVideoInputSegment1 withInsertAt(long insertAt) {
        this.insertAt = insertAt;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PullVideoInputSegment1 other = (PullVideoInputSegment1) o;
        return 
            Utils.enhancedDeepEquals(this.url, other.url) &&
            Utils.enhancedDeepEquals(this.insertAt, other.insertAt);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            url, insertAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PullVideoInputSegment1.class,
                "url", url,
                "insertAt", insertAt);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String url;

        private long insertAt;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The URL of the **video segment** to be added.
         * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve and
         * process the segment successfully.
         * Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and performance.
         */
        public Builder url(@Nonnull String url) {
            this.url = Utils.checkNotNull(url, "url");
            return this;
        }

        /**
         * The timestamp(in seconds) at which the segment must be inserted.
         */
        public Builder insertAt(long insertAt) {
            this.insertAt = insertAt;
            return this;
        }

        public PullVideoInputSegment1 build() {
            return new PullVideoInputSegment1(
                url, insertAt);
        }

    }
}
