/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.HasSecurity;
import org.openapis.openapi.utils.FastpixMetadata;
import org.openapis.openapi.utils.Utils;


public class Security implements HasSecurity {

    @FastpixMetadata("security:scheme=true,type=http,subtype=basic,name=username")
    private String username;


    @FastpixMetadata("security:scheme=true,type=http,subtype=basic,name=password")
    private String password;

    @JsonCreator
    public Security(
            @Nonnull String username,
            @Nonnull String password) {
        this.username = Optional.ofNullable(username)
            .orElseThrow(() -> new IllegalArgumentException("username cannot be null"));
        this.password = Optional.ofNullable(password)
            .orElseThrow(() -> new IllegalArgumentException("password cannot be null"));
    }

    public String username() {
        return this.username;
    }

    public String password() {
        return this.password;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Security withUsername(@Nonnull String username) {
        this.username = Utils.checkNotNull(username, "username");
        return this;
    }


    public Security withPassword(@Nonnull String password) {
        this.password = Utils.checkNotNull(password, "password");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Security other = (Security) o;
        return 
            Utils.enhancedDeepEquals(this.username, other.username) &&
            Utils.enhancedDeepEquals(this.password, other.password);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            username, password);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Security.class,
                "username", username,
                "password", password);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String username;

        private String password;

        private Builder() {
          // force use of static builder() method
        }

        public Builder username(@Nonnull String username) {
            this.username = Utils.checkNotNull(username, "username");
            return this;
        }

        public Builder password(@Nonnull String password) {
            this.password = Utils.checkNotNull(password, "password");
            return this;
        }

        public Security build() {
            return new Security(
                username, password);
        }

    }
}
