/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * SimulcastResponseData
 * 
 * <p>Displays the result of the request.
 */
public class SimulcastResponseData {
    /**
     * When you create the new simulcast, FastPix assign a universal unique identifier which can contain a
     * maximum of 255 characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("simulcastId")
    private String simulcastId;

    /**
     * The RTMPS hostname, combined with the application name, is crucial for connecting to third-party
     * live streaming services and transmitting the live stream.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    private String url;

    /**
     * A unique stream key is generated for streaming, allowing the user to start streaming on any
     * third-party platform using this key.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("streamKey")
    private String streamKey;

    /**
     * When the value is true, the simulcast must be enabled for the given stream
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isEnabled")
    private Boolean isEnabled;

    /**
     * You can search for videos with specific key value pairs using metadata, when you tag a video in
     * "key":"value"s pairs. Dynamic metadata allows you to define a key that allows any value pair. You
     * can have maximum of 255 characters and upto 10 entries are allowed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private Map<String, String> metadata;

    @JsonCreator
    public SimulcastResponseData(
            @JsonProperty("simulcastId") @Nullable String simulcastId,
            @JsonProperty("url") @Nullable String url,
            @JsonProperty("streamKey") @Nullable String streamKey,
            @JsonProperty("isEnabled") @Nullable Boolean isEnabled,
            @JsonProperty("metadata") @Nullable Map<String, String> metadata) {
        this.simulcastId = simulcastId;
        this.url = url;
        this.streamKey = streamKey;
        this.isEnabled = isEnabled;
        this.metadata = metadata;
    }
    
    public SimulcastResponseData() {
        this(null, null, null,
            null, null);
    }

    /**
     * When you create the new simulcast, FastPix assign a universal unique identifier which can contain a
     * maximum of 255 characters.
     */
    public Optional<String> simulcastId() {
        return Optional.ofNullable(this.simulcastId);
    }

    /**
     * The RTMPS hostname, combined with the application name, is crucial for connecting to third-party
     * live streaming services and transmitting the live stream.
     */
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }

    /**
     * A unique stream key is generated for streaming, allowing the user to start streaming on any
     * third-party platform using this key.
     */
    public Optional<String> streamKey() {
        return Optional.ofNullable(this.streamKey);
    }

    /**
     * When the value is true, the simulcast must be enabled for the given stream
     */
    @JsonIgnore
    public Optional<Boolean> isEnabled() {
        return Optional.ofNullable(this.isEnabled);
    }

    /**
     * You can search for videos with specific key value pairs using metadata, when you tag a video in
     * "key":"value"s pairs. Dynamic metadata allows you to define a key that allows any value pair. You
     * can have maximum of 255 characters and upto 10 entries are allowed.
     */
    public Optional<Map<String, String>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * When you create the new simulcast, FastPix assign a universal unique identifier which can contain a
     * maximum of 255 characters.
     */
    public SimulcastResponseData withSimulcastId(@Nullable String simulcastId) {
        this.simulcastId = simulcastId;
        return this;
    }


    /**
     * The RTMPS hostname, combined with the application name, is crucial for connecting to third-party
     * live streaming services and transmitting the live stream.
     */
    public SimulcastResponseData withUrl(@Nullable String url) {
        this.url = url;
        return this;
    }


    /**
     * A unique stream key is generated for streaming, allowing the user to start streaming on any
     * third-party platform using this key.
     */
    public SimulcastResponseData withStreamKey(@Nullable String streamKey) {
        this.streamKey = streamKey;
        return this;
    }


    /**
     * When the value is true, the simulcast must be enabled for the given stream
     */
    public SimulcastResponseData withIsEnabled(@Nullable Boolean isEnabled) {
        this.isEnabled = isEnabled;
        return this;
    }


    /**
     * You can search for videos with specific key value pairs using metadata, when you tag a video in
     * "key":"value"s pairs. Dynamic metadata allows you to define a key that allows any value pair. You
     * can have maximum of 255 characters and upto 10 entries are allowed.
     */
    public SimulcastResponseData withMetadata(@Nullable Map<String, String> metadata) {
        this.metadata = metadata;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SimulcastResponseData other = (SimulcastResponseData) o;
        return 
            Utils.enhancedDeepEquals(this.simulcastId, other.simulcastId) &&
            Utils.enhancedDeepEquals(this.url, other.url) &&
            Utils.enhancedDeepEquals(this.streamKey, other.streamKey) &&
            Utils.enhancedDeepEquals(this.isEnabled, other.isEnabled) &&
            Utils.enhancedDeepEquals(this.metadata, other.metadata);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            simulcastId, url, streamKey,
            isEnabled, metadata);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SimulcastResponseData.class,
                "simulcastId", simulcastId,
                "url", url,
                "streamKey", streamKey,
                "isEnabled", isEnabled,
                "metadata", metadata);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String simulcastId;

        private String url;

        private String streamKey;

        private Boolean isEnabled;

        private Map<String, String> metadata;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * When you create the new simulcast, FastPix assign a universal unique identifier which can contain a
         * maximum of 255 characters.
         */
        public Builder simulcastId(@Nullable String simulcastId) {
            this.simulcastId = simulcastId;
            return this;
        }

        /**
         * The RTMPS hostname, combined with the application name, is crucial for connecting to third-party
         * live streaming services and transmitting the live stream.
         */
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }

        /**
         * A unique stream key is generated for streaming, allowing the user to start streaming on any
         * third-party platform using this key.
         */
        public Builder streamKey(@Nullable String streamKey) {
            this.streamKey = streamKey;
            return this;
        }

        /**
         * When the value is true, the simulcast must be enabled for the given stream
         */
        public Builder isEnabled(@Nullable Boolean isEnabled) {
            this.isEnabled = isEnabled;
            return this;
        }

        /**
         * You can search for videos with specific key value pairs using metadata, when you tag a video in
         * "key":"value"s pairs. Dynamic metadata allows you to define a key that allows any value pair. You
         * can have maximum of 255 characters and upto 10 entries are allowed.
         */
        public Builder metadata(@Nullable Map<String, String> metadata) {
            this.metadata = metadata;
            return this;
        }

        public SimulcastResponseData build() {
            return new SimulcastResponseData(
                simulcastId, url, streamKey,
                isEnabled, metadata);
        }

    }
}
