/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * SubtitleTrackType
 * 
 * <p>Defines the type of input track.
 */
public class SubtitleTrackType {

    public static final SubtitleTrackType SUBTITLE = new SubtitleTrackType("subtitle");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, SubtitleTrackType> values = createValuesMap();
    private static final Map<String, SubtitleTrackTypeEnum> enums = createEnumsMap();

    private final String value;

    private SubtitleTrackType(String value) {
        this.value = value;
    }

    /**
     * Returns a SubtitleTrackType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as SubtitleTrackType
     */ 
    @JsonCreator
    public static SubtitleTrackType of(String value) {
        synchronized (SubtitleTrackType.class) {
            return values.computeIfAbsent(value, v -> new SubtitleTrackType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<SubtitleTrackTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        SubtitleTrackType other = (SubtitleTrackType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "SubtitleTrackType [value=" + value + "]";
    }

    // return an array just like an enum
    public static SubtitleTrackType[] values() {
        synchronized (SubtitleTrackType.class) {
            return values.values().toArray(new SubtitleTrackType[] {});
        }
    }

    private static final Map<String, SubtitleTrackType> createValuesMap() {
        Map<String, SubtitleTrackType> map = new LinkedHashMap<>();
        map.put("subtitle", SUBTITLE);
        return map;
    }

    private static final Map<String, SubtitleTrackTypeEnum> createEnumsMap() {
        Map<String, SubtitleTrackTypeEnum> map = new HashMap<>();
        map.put("subtitle", SubtitleTrackTypeEnum.SUBTITLE);
        return map;
    }
    
    
    public enum SubtitleTrackTypeEnum {

        SUBTITLE("subtitle"),;

        private final String value;

        private SubtitleTrackTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

