/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class SummaryResponse {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mediaId")
    private String mediaId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isSummaryEnabled")
    private Boolean isSummaryEnabled;

    @JsonCreator
    public SummaryResponse(
            @JsonProperty("mediaId") @Nullable String mediaId,
            @JsonProperty("isSummaryEnabled") @Nullable Boolean isSummaryEnabled) {
        this.mediaId = mediaId;
        this.isSummaryEnabled = isSummaryEnabled;
    }
    
    public SummaryResponse() {
        this(null, null);
    }

    public Optional<String> mediaId() {
        return Optional.ofNullable(this.mediaId);
    }

    @JsonIgnore
    public Optional<Boolean> isSummaryEnabled() {
        return Optional.ofNullable(this.isSummaryEnabled);
    }

    public static Builder builder() {
        return new Builder();
    }


    public SummaryResponse withMediaId(@Nullable String mediaId) {
        this.mediaId = mediaId;
        return this;
    }


    public SummaryResponse withIsSummaryEnabled(@Nullable Boolean isSummaryEnabled) {
        this.isSummaryEnabled = isSummaryEnabled;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SummaryResponse other = (SummaryResponse) o;
        return 
            Utils.enhancedDeepEquals(this.mediaId, other.mediaId) &&
            Utils.enhancedDeepEquals(this.isSummaryEnabled, other.isSummaryEnabled);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            mediaId, isSummaryEnabled);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SummaryResponse.class,
                "mediaId", mediaId,
                "isSummaryEnabled", isSummaryEnabled);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String mediaId;

        private Boolean isSummaryEnabled;

        private Builder() {
          // force use of static builder() method
        }

        public Builder mediaId(@Nullable String mediaId) {
            this.mediaId = mediaId;
            return this;
        }

        public Builder isSummaryEnabled(@Nullable Boolean isSummaryEnabled) {
            this.isSummaryEnabled = isSummaryEnabled;
            return this;
        }

        public SummaryResponse build() {
            return new SummaryResponse(
                mediaId, isSummaryEnabled);
        }

    }
}
