/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class TracksSubtitles {
    /**
     * Current status of the generated subtitle track.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private String status;

    /**
     * URL of the generated subtitle file (VTT). Null while preparing.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    private JsonNullable<String> url;

    @JsonCreator
    public TracksSubtitles(
            @JsonProperty("status") @Nullable String status,
            @JsonProperty("url") @Nullable JsonNullable<String> url) {
        this.status = status;
        this.url = Optional.ofNullable(url)
            .orElse(JsonNullable.undefined());
    }
    
    public TracksSubtitles() {
        this(null, null);
    }

    /**
     * Current status of the generated subtitle track.
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * URL of the generated subtitle file (VTT). Null while preparing.
     */
    public JsonNullable<String> url() {
        return this.url;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Current status of the generated subtitle track.
     */
    public TracksSubtitles withStatus(@Nullable String status) {
        this.status = status;
        return this;
    }


    /**
     * URL of the generated subtitle file (VTT). Null while preparing.
     */
    public TracksSubtitles withUrl(@Nullable String url) {
        this.url = JsonNullable.of(url);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TracksSubtitles other = (TracksSubtitles) o;
        return 
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.url, other.url);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            status, url);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TracksSubtitles.class,
                "status", status,
                "url", url);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String status;

        private JsonNullable<String> url;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Current status of the generated subtitle track.
         */
        public Builder status(@Nullable String status) {
            this.status = status;
            return this;
        }

        /**
         * URL of the generated subtitle file (VTT). Null while preparing.
         */
        public Builder url(@Nullable String url) {
            this.url = JsonNullable.of(url);
            return this;
        }

        public TracksSubtitles build() {
            return new TracksSubtitles(
                status, url);
        }

    }
}
