/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import org.openapis.openapi.utils.OneOfDeserializer;
import org.openapis.openapi.utils.TypedObject;
import org.openapis.openapi.utils.Utils.JsonShape;
import org.openapis.openapi.utils.Utils.TypeReferenceWithShape;
import org.openapis.openapi.utils.Utils;

/**
 * UniqueViewersEffectedPercentage
 * 
 * <p>percentage of unique viewers affected by the specific error.
 */
@JsonDeserialize(using = UniqueViewersEffectedPercentage._Deserializer.class)
public class UniqueViewersEffectedPercentage {

    @JsonValue
    private final TypedObject value;
    
    private UniqueViewersEffectedPercentage(TypedObject value) {
        this.value = value;
    }

    public static UniqueViewersEffectedPercentage of(long value) {
        return new UniqueViewersEffectedPercentage(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static UniqueViewersEffectedPercentage of(double value) {
        return new UniqueViewersEffectedPercentage(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code long},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code long} value, or empty if not of this type
     */
    public Optional<java.lang.Long> asLong() {
        if (value.value() instanceof java.lang.Long) {
            return Optional.of((java.lang.Long) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code double},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code double} value, or empty if not of this type
     */
    public Optional<java.lang.Double> asDouble() {
        if (value.value() instanceof java.lang.Double) {
            return Optional.of((java.lang.Double) value.value());
        }
        return Optional.empty();
    }
   /**
    * Returns an {@link Optional} containing the value as a {@code JsonNode}.
    * This accessor returns the raw JSON when the value doesn't match any of the defined union types.
    *
    * @return an {@link Optional} containing the {@code JsonNode} value, or empty if value matched a known type
    */
   public Optional<JsonNode> asJson() {
       if (value.value() instanceof JsonNode) {
           return Optional.of((JsonNode) value.value());
       }
       return Optional.empty();
   }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UniqueViewersEffectedPercentage other = (UniqueViewersEffectedPercentage) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<UniqueViewersEffectedPercentage> {

        public _Deserializer() {
            super(UniqueViewersEffectedPercentage.class, false,
                  TypeReferenceWithShape.of(new TypeReference<Long>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Double>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(UniqueViewersEffectedPercentage.class,
                "value", value);
    }

}

