/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.databind.JsonNode;
import java.lang.Override;
import java.lang.String;
import org.openapis.openapi.utils.UnknownType;


public class UnknownPlaylistCreatedSchema extends UnknownType implements PlaylistCreatedSchema {

    @JsonCreator
    public UnknownPlaylistCreatedSchema(JsonNode rawNode) {
        super(rawNode);
    }

    @Override
    public String type() {
        return extractDiscriminator("type").orElse("UNKNOWN");
    }

}