/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * UnusedUploadsPlaybackId
 * 
 * <p>A collection of Playback ID objects utilized for crafting HLS playback urls.
 */
public class UnusedUploadsPlaybackId {
    /**
     * Access policy for media content
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("accessPolicy")
    private AccessPolicy accessPolicy;

    /**
     * Controls access based on domains and user agents. Defines a default policy (either "allow" or
     * "deny") and provides lists for explicitly allowed or denied domains and user agents.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("accessRestrictions")
    private UnusedUploadsPlaybackIdAccessRestrictions accessRestrictions;

    @JsonCreator
    public UnusedUploadsPlaybackId(
            @JsonProperty("accessPolicy") @Nullable AccessPolicy accessPolicy,
            @JsonProperty("accessRestrictions") @Nullable UnusedUploadsPlaybackIdAccessRestrictions accessRestrictions) {
        this.accessPolicy = accessPolicy;
        this.accessRestrictions = accessRestrictions;
    }
    
    public UnusedUploadsPlaybackId() {
        this(null, null);
    }

    /**
     * Access policy for media content
     */
    public Optional<AccessPolicy> accessPolicy() {
        return Optional.ofNullable(this.accessPolicy);
    }

    /**
     * Controls access based on domains and user agents. Defines a default policy (either "allow" or
     * "deny") and provides lists for explicitly allowed or denied domains and user agents.
     */
    public Optional<UnusedUploadsPlaybackIdAccessRestrictions> accessRestrictions() {
        return Optional.ofNullable(this.accessRestrictions);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Access policy for media content
     */
    public UnusedUploadsPlaybackId withAccessPolicy(@Nullable AccessPolicy accessPolicy) {
        this.accessPolicy = accessPolicy;
        return this;
    }


    /**
     * Controls access based on domains and user agents. Defines a default policy (either "allow" or
     * "deny") and provides lists for explicitly allowed or denied domains and user agents.
     */
    public UnusedUploadsPlaybackId withAccessRestrictions(@Nullable UnusedUploadsPlaybackIdAccessRestrictions accessRestrictions) {
        this.accessRestrictions = accessRestrictions;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UnusedUploadsPlaybackId other = (UnusedUploadsPlaybackId) o;
        return 
            Utils.enhancedDeepEquals(this.accessPolicy, other.accessPolicy) &&
            Utils.enhancedDeepEquals(this.accessRestrictions, other.accessRestrictions);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accessPolicy, accessRestrictions);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UnusedUploadsPlaybackId.class,
                "accessPolicy", accessPolicy,
                "accessRestrictions", accessRestrictions);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AccessPolicy accessPolicy;

        private UnusedUploadsPlaybackIdAccessRestrictions accessRestrictions;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Access policy for media content
         */
        public Builder accessPolicy(@Nullable AccessPolicy accessPolicy) {
            this.accessPolicy = accessPolicy;
            return this;
        }

        /**
         * Controls access based on domains and user agents. Defines a default policy (either "allow" or
         * "deny") and provides lists for explicitly allowed or denied domains and user agents.
         */
        public Builder accessRestrictions(@Nullable UnusedUploadsPlaybackIdAccessRestrictions accessRestrictions) {
            this.accessRestrictions = accessRestrictions;
            return this;
        }

        public UnusedUploadsPlaybackId build() {
            return new UnusedUploadsPlaybackId(
                accessPolicy, accessRestrictions);
        }

    }
}
