/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * UserAgentRestrictions
 * 
 * <p>Restrictions based on the user agent
 */
public class UserAgentRestrictions {
    /**
     * Policy action type
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("defaultPolicy")
    private PolicyAction defaultPolicy;

    /**
     * A list of user agents that are explicitly allowed access
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("allow")
    private List<String> allow;

    /**
     * A list of user agents that are explicitly denied access
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deny")
    private List<String> deny;

    @JsonCreator
    public UserAgentRestrictions(
            @JsonProperty("defaultPolicy") @Nullable PolicyAction defaultPolicy,
            @JsonProperty("allow") @Nullable List<String> allow,
            @JsonProperty("deny") @Nullable List<String> deny) {
        this.defaultPolicy = defaultPolicy;
        this.allow = allow;
        this.deny = deny;
    }
    
    public UserAgentRestrictions() {
        this(null, null, null);
    }

    /**
     * Policy action type
     */
    public Optional<PolicyAction> defaultPolicy() {
        return Optional.ofNullable(this.defaultPolicy);
    }

    /**
     * A list of user agents that are explicitly allowed access
     */
    public Optional<List<String>> allow() {
        return Optional.ofNullable(this.allow);
    }

    /**
     * A list of user agents that are explicitly denied access
     */
    public Optional<List<String>> deny() {
        return Optional.ofNullable(this.deny);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Policy action type
     */
    public UserAgentRestrictions withDefaultPolicy(@Nullable PolicyAction defaultPolicy) {
        this.defaultPolicy = defaultPolicy;
        return this;
    }


    /**
     * A list of user agents that are explicitly allowed access
     */
    public UserAgentRestrictions withAllow(@Nullable List<String> allow) {
        this.allow = allow;
        return this;
    }


    /**
     * A list of user agents that are explicitly denied access
     */
    public UserAgentRestrictions withDeny(@Nullable List<String> deny) {
        this.deny = deny;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserAgentRestrictions other = (UserAgentRestrictions) o;
        return 
            Utils.enhancedDeepEquals(this.defaultPolicy, other.defaultPolicy) &&
            Utils.enhancedDeepEquals(this.allow, other.allow) &&
            Utils.enhancedDeepEquals(this.deny, other.deny);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            defaultPolicy, allow, deny);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UserAgentRestrictions.class,
                "defaultPolicy", defaultPolicy,
                "allow", allow,
                "deny", deny);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PolicyAction defaultPolicy;

        private List<String> allow;

        private List<String> deny;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Policy action type
         */
        public Builder defaultPolicy(@Nullable PolicyAction defaultPolicy) {
            this.defaultPolicy = defaultPolicy;
            return this;
        }

        /**
         * A list of user agents that are explicitly allowed access
         */
        public Builder allow(@Nullable List<String> allow) {
            this.allow = allow;
            return this;
        }

        /**
         * A list of user agents that are explicitly denied access
         */
        public Builder deny(@Nullable List<String> deny) {
            this.deny = deny;
            return this;
        }

        public UserAgentRestrictions build() {
            return new UserAgentRestrictions(
                defaultPolicy, allow, deny);
        }

    }
}
