/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class VideoInputSegment2 {
    /**
     * URL of the segment to be added.
     */
    @JsonProperty("url")
    private String url;

    /**
     * Flag indicating the segment should be inserted at the end.
     */
    @JsonProperty("insertAtEnd")
    private boolean insertAtEnd;

    @JsonCreator
    public VideoInputSegment2(
            @JsonProperty("url") @Nonnull String url,
            @JsonProperty("insertAtEnd") boolean insertAtEnd) {
        this.url = Optional.ofNullable(url)
            .orElseThrow(() -> new IllegalArgumentException("url cannot be null"));
        this.insertAtEnd = insertAtEnd;
    }

    /**
     * URL of the segment to be added.
     */
    public String url() {
        return this.url;
    }

    /**
     * Flag indicating the segment should be inserted at the end.
     */
    public boolean insertAtEnd() {
        return this.insertAtEnd;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * URL of the segment to be added.
     */
    public VideoInputSegment2 withUrl(@Nonnull String url) {
        this.url = Utils.checkNotNull(url, "url");
        return this;
    }


    /**
     * Flag indicating the segment should be inserted at the end.
     */
    public VideoInputSegment2 withInsertAtEnd(boolean insertAtEnd) {
        this.insertAtEnd = insertAtEnd;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VideoInputSegment2 other = (VideoInputSegment2) o;
        return 
            Utils.enhancedDeepEquals(this.url, other.url) &&
            Utils.enhancedDeepEquals(this.insertAtEnd, other.insertAtEnd);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            url, insertAtEnd);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VideoInputSegment2.class,
                "url", url,
                "insertAtEnd", insertAtEnd);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String url;

        private boolean insertAtEnd;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * URL of the segment to be added.
         */
        public Builder url(@Nonnull String url) {
            this.url = Utils.checkNotNull(url, "url");
            return this;
        }

        /**
         * Flag indicating the segment should be inserted at the end.
         */
        public Builder insertAtEnd(boolean insertAtEnd) {
            this.insertAtEnd = insertAtEnd;
            return this;
        }

        public VideoInputSegment2 build() {
            return new VideoInputSegment2(
                url, insertAtEnd);
        }

    }
}
