/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * ViewsCountResponseData
 * 
 * <p>Contains the view count details.
 */
public class ViewsCountResponseData {
    /**
     * Number of views for the stream or resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("views")
    private Long views;

    @JsonCreator
    public ViewsCountResponseData(
            @JsonProperty("views") @Nullable Long views) {
        this.views = views;
    }
    
    public ViewsCountResponseData() {
        this(null);
    }

    /**
     * Number of views for the stream or resource.
     */
    public Optional<Long> views() {
        return Optional.ofNullable(this.views);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Number of views for the stream or resource.
     */
    public ViewsCountResponseData withViews(@Nullable Long views) {
        this.views = views;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ViewsCountResponseData other = (ViewsCountResponseData) o;
        return 
            Utils.enhancedDeepEquals(this.views, other.views);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            views);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ViewsCountResponseData.class,
                "views", views);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Long views;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Number of views for the stream or resource.
         */
        public Builder views(@Nullable Long views) {
            this.views = views;
            return this;
        }

        public ViewsCountResponseData build() {
            return new ViewsCountResponseData(
                views);
        }

    }
}
