/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class ViewsList {
    /**
     * The unique identifier for the viewing session of the user.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("viewId")
    private String viewId;

    /**
     * Operating System signifies the software platform utilized by the viewer
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("operatingSystem")
    private JsonNullable<String> operatingSystem;

    /**
     * The browser name of the viewer.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("application")
    private JsonNullable<String> application;

    /**
     * The start timestamp of the video view.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("viewStartTime")
    private JsonNullable<String> viewStartTime;

    /**
     * The end timestamp of the video view.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("viewEndTime")
    private JsonNullable<String> viewEndTime;

    /**
     * The title of the Video.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("videoTitle")
    private JsonNullable<String> videoTitle;

    /**
     * The code which represents specific issues or failures that occur during playback. These can be
     * implementation specific.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errorCode")
    private JsonNullable<String> errorCode;

    /**
     * The notifications or messages that inform users or developers about issues or failures that have
     * occurred during the playback representing error codes.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errorMessage")
    private JsonNullable<String> errorMessage;

    /**
     * The unique identifier for the error that occurred during playback.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errorId")
    private JsonNullable<String> errorId;

    /**
     * Country of the viewer.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    private JsonNullable<String> country;

    /**
     * The watch time represents the time spent watching the video including staruptime, playback time
     * ,buffering time.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("viewWatchTime")
    private JsonNullable<Double> viewWatchTime;

    /**
     * The viewer experience encapsulated in the form of score while watching the video.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("QoeScore")
    private JsonNullable<Double> qoeScore;

    @JsonCreator
    public ViewsList(
            @JsonProperty("viewId") @Nullable String viewId,
            @JsonProperty("operatingSystem") @Nullable JsonNullable<String> operatingSystem,
            @JsonProperty("application") @Nullable JsonNullable<String> application,
            @JsonProperty("viewStartTime") @Nullable JsonNullable<String> viewStartTime,
            @JsonProperty("viewEndTime") @Nullable JsonNullable<String> viewEndTime,
            @JsonProperty("videoTitle") @Nullable JsonNullable<String> videoTitle,
            @JsonProperty("errorCode") @Nullable JsonNullable<String> errorCode,
            @JsonProperty("errorMessage") @Nullable JsonNullable<String> errorMessage,
            @JsonProperty("errorId") @Nullable JsonNullable<String> errorId,
            @JsonProperty("country") @Nullable JsonNullable<String> country,
            @JsonProperty("viewWatchTime") @Nullable JsonNullable<Double> viewWatchTime,
            @JsonProperty("QoeScore") @Nullable JsonNullable<Double> qoeScore) {
        this.viewId = viewId;
        this.operatingSystem = Optional.ofNullable(operatingSystem)
            .orElse(JsonNullable.undefined());
        this.application = Optional.ofNullable(application)
            .orElse(JsonNullable.undefined());
        this.viewStartTime = Optional.ofNullable(viewStartTime)
            .orElse(JsonNullable.undefined());
        this.viewEndTime = Optional.ofNullable(viewEndTime)
            .orElse(JsonNullable.undefined());
        this.videoTitle = Optional.ofNullable(videoTitle)
            .orElse(JsonNullable.undefined());
        this.errorCode = Optional.ofNullable(errorCode)
            .orElse(JsonNullable.undefined());
        this.errorMessage = Optional.ofNullable(errorMessage)
            .orElse(JsonNullable.undefined());
        this.errorId = Optional.ofNullable(errorId)
            .orElse(JsonNullable.undefined());
        this.country = Optional.ofNullable(country)
            .orElse(JsonNullable.undefined());
        this.viewWatchTime = Optional.ofNullable(viewWatchTime)
            .orElse(JsonNullable.undefined());
        this.qoeScore = Optional.ofNullable(qoeScore)
            .orElse(JsonNullable.undefined());
    }
    
    public ViewsList() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null);
    }

    /**
     * The unique identifier for the viewing session of the user.
     */
    public Optional<String> viewId() {
        return Optional.ofNullable(this.viewId);
    }

    /**
     * Operating System signifies the software platform utilized by the viewer
     */
    public JsonNullable<String> operatingSystem() {
        return this.operatingSystem;
    }

    /**
     * The browser name of the viewer.
     */
    public JsonNullable<String> application() {
        return this.application;
    }

    /**
     * The start timestamp of the video view.
     */
    public JsonNullable<String> viewStartTime() {
        return this.viewStartTime;
    }

    /**
     * The end timestamp of the video view.
     */
    public JsonNullable<String> viewEndTime() {
        return this.viewEndTime;
    }

    /**
     * The title of the Video.
     */
    public JsonNullable<String> videoTitle() {
        return this.videoTitle;
    }

    /**
     * The code which represents specific issues or failures that occur during playback. These can be
     * implementation specific.
     */
    public JsonNullable<String> errorCode() {
        return this.errorCode;
    }

    /**
     * The notifications or messages that inform users or developers about issues or failures that have
     * occurred during the playback representing error codes.
     */
    public JsonNullable<String> errorMessage() {
        return this.errorMessage;
    }

    /**
     * The unique identifier for the error that occurred during playback.
     */
    public JsonNullable<String> errorId() {
        return this.errorId;
    }

    /**
     * Country of the viewer.
     */
    public JsonNullable<String> country() {
        return this.country;
    }

    /**
     * The watch time represents the time spent watching the video including staruptime, playback time
     * ,buffering time.
     */
    public JsonNullable<Double> viewWatchTime() {
        return this.viewWatchTime;
    }

    /**
     * The viewer experience encapsulated in the form of score while watching the video.
     */
    public JsonNullable<Double> qoeScore() {
        return this.qoeScore;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique identifier for the viewing session of the user.
     */
    public ViewsList withViewId(@Nullable String viewId) {
        this.viewId = viewId;
        return this;
    }


    /**
     * Operating System signifies the software platform utilized by the viewer
     */
    public ViewsList withOperatingSystem(@Nullable String operatingSystem) {
        this.operatingSystem = JsonNullable.of(operatingSystem);
        return this;
    }


    /**
     * The browser name of the viewer.
     */
    public ViewsList withApplication(@Nullable String application) {
        this.application = JsonNullable.of(application);
        return this;
    }


    /**
     * The start timestamp of the video view.
     */
    public ViewsList withViewStartTime(@Nullable String viewStartTime) {
        this.viewStartTime = JsonNullable.of(viewStartTime);
        return this;
    }


    /**
     * The end timestamp of the video view.
     */
    public ViewsList withViewEndTime(@Nullable String viewEndTime) {
        this.viewEndTime = JsonNullable.of(viewEndTime);
        return this;
    }


    /**
     * The title of the Video.
     */
    public ViewsList withVideoTitle(@Nullable String videoTitle) {
        this.videoTitle = JsonNullable.of(videoTitle);
        return this;
    }


    /**
     * The code which represents specific issues or failures that occur during playback. These can be
     * implementation specific.
     */
    public ViewsList withErrorCode(@Nullable String errorCode) {
        this.errorCode = JsonNullable.of(errorCode);
        return this;
    }


    /**
     * The notifications or messages that inform users or developers about issues or failures that have
     * occurred during the playback representing error codes.
     */
    public ViewsList withErrorMessage(@Nullable String errorMessage) {
        this.errorMessage = JsonNullable.of(errorMessage);
        return this;
    }


    /**
     * The unique identifier for the error that occurred during playback.
     */
    public ViewsList withErrorId(@Nullable String errorId) {
        this.errorId = JsonNullable.of(errorId);
        return this;
    }


    /**
     * Country of the viewer.
     */
    public ViewsList withCountry(@Nullable String country) {
        this.country = JsonNullable.of(country);
        return this;
    }


    /**
     * The watch time represents the time spent watching the video including staruptime, playback time
     * ,buffering time.
     */
    public ViewsList withViewWatchTime(@Nullable Double viewWatchTime) {
        this.viewWatchTime = JsonNullable.of(viewWatchTime);
        return this;
    }


    /**
     * The viewer experience encapsulated in the form of score while watching the video.
     */
    public ViewsList withQoeScore(@Nullable Double qoeScore) {
        this.qoeScore = JsonNullable.of(qoeScore);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ViewsList other = (ViewsList) o;
        return 
            Utils.enhancedDeepEquals(this.viewId, other.viewId) &&
            Utils.enhancedDeepEquals(this.operatingSystem, other.operatingSystem) &&
            Utils.enhancedDeepEquals(this.application, other.application) &&
            Utils.enhancedDeepEquals(this.viewStartTime, other.viewStartTime) &&
            Utils.enhancedDeepEquals(this.viewEndTime, other.viewEndTime) &&
            Utils.enhancedDeepEquals(this.videoTitle, other.videoTitle) &&
            Utils.enhancedDeepEquals(this.errorCode, other.errorCode) &&
            Utils.enhancedDeepEquals(this.errorMessage, other.errorMessage) &&
            Utils.enhancedDeepEquals(this.errorId, other.errorId) &&
            Utils.enhancedDeepEquals(this.country, other.country) &&
            Utils.enhancedDeepEquals(this.viewWatchTime, other.viewWatchTime) &&
            Utils.enhancedDeepEquals(this.qoeScore, other.qoeScore);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            viewId, operatingSystem, application,
            viewStartTime, viewEndTime, videoTitle,
            errorCode, errorMessage, errorId,
            country, viewWatchTime, qoeScore);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ViewsList.class,
                "viewId", viewId,
                "operatingSystem", operatingSystem,
                "application", application,
                "viewStartTime", viewStartTime,
                "viewEndTime", viewEndTime,
                "videoTitle", videoTitle,
                "errorCode", errorCode,
                "errorMessage", errorMessage,
                "errorId", errorId,
                "country", country,
                "viewWatchTime", viewWatchTime,
                "qoeScore", qoeScore);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String viewId;

        private JsonNullable<String> operatingSystem;

        private JsonNullable<String> application;

        private JsonNullable<String> viewStartTime;

        private JsonNullable<String> viewEndTime;

        private JsonNullable<String> videoTitle;

        private JsonNullable<String> errorCode;

        private JsonNullable<String> errorMessage;

        private JsonNullable<String> errorId;

        private JsonNullable<String> country;

        private JsonNullable<Double> viewWatchTime;

        private JsonNullable<Double> qoeScore;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The unique identifier for the viewing session of the user.
         */
        public Builder viewId(@Nullable String viewId) {
            this.viewId = viewId;
            return this;
        }

        /**
         * Operating System signifies the software platform utilized by the viewer
         */
        public Builder operatingSystem(@Nullable String operatingSystem) {
            this.operatingSystem = JsonNullable.of(operatingSystem);
            return this;
        }

        /**
         * The browser name of the viewer.
         */
        public Builder application(@Nullable String application) {
            this.application = JsonNullable.of(application);
            return this;
        }

        /**
         * The start timestamp of the video view.
         */
        public Builder viewStartTime(@Nullable String viewStartTime) {
            this.viewStartTime = JsonNullable.of(viewStartTime);
            return this;
        }

        /**
         * The end timestamp of the video view.
         */
        public Builder viewEndTime(@Nullable String viewEndTime) {
            this.viewEndTime = JsonNullable.of(viewEndTime);
            return this;
        }

        /**
         * The title of the Video.
         */
        public Builder videoTitle(@Nullable String videoTitle) {
            this.videoTitle = JsonNullable.of(videoTitle);
            return this;
        }

        /**
         * The code which represents specific issues or failures that occur during playback. These can be
         * implementation specific.
         */
        public Builder errorCode(@Nullable String errorCode) {
            this.errorCode = JsonNullable.of(errorCode);
            return this;
        }

        /**
         * The notifications or messages that inform users or developers about issues or failures that have
         * occurred during the playback representing error codes.
         */
        public Builder errorMessage(@Nullable String errorMessage) {
            this.errorMessage = JsonNullable.of(errorMessage);
            return this;
        }

        /**
         * The unique identifier for the error that occurred during playback.
         */
        public Builder errorId(@Nullable String errorId) {
            this.errorId = JsonNullable.of(errorId);
            return this;
        }

        /**
         * Country of the viewer.
         */
        public Builder country(@Nullable String country) {
            this.country = JsonNullable.of(country);
            return this;
        }

        /**
         * The watch time represents the time spent watching the video including staruptime, playback time
         * ,buffering time.
         */
        public Builder viewWatchTime(@Nullable Double viewWatchTime) {
            this.viewWatchTime = JsonNullable.of(viewWatchTime);
            return this;
        }

        /**
         * The viewer experience encapsulated in the form of score while watching the video.
         */
        public Builder qoeScore(@Nullable Double qoeScore) {
            this.qoeScore = JsonNullable.of(qoeScore);
            return this;
        }

        public ViewsList build() {
            return new ViewsList(
                viewId, operatingSystem, application,
                viewStartTime, viewEndTime, videoTitle,
                errorCode, errorMessage, errorId,
                country, viewWatchTime, qoeScore);
        }

    }
}
