/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * ViewsByTopContentDetails
 * 
 * <p>Retrieves a list of the top video views
 */
public class ViewsByTopContentDetails {
    /**
     * Title of the video
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("videoTitle")
    private String videoTitle;

    /**
     * Total count of view sessions for a particular video content.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("views")
    private Long views;

    /**
     * Total count of unique video viewers for particular video content.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uniqueViews")
    private Long uniqueViews;

    @JsonCreator
    public ViewsByTopContentDetails(
            @JsonProperty("videoTitle") @Nullable String videoTitle,
            @JsonProperty("views") @Nullable Long views,
            @JsonProperty("uniqueViews") @Nullable Long uniqueViews) {
        this.videoTitle = videoTitle;
        this.views = views;
        this.uniqueViews = uniqueViews;
    }
    
    public ViewsByTopContentDetails() {
        this(null, null, null);
    }

    /**
     * Title of the video
     */
    public Optional<String> videoTitle() {
        return Optional.ofNullable(this.videoTitle);
    }

    /**
     * Total count of view sessions for a particular video content.
     */
    public Optional<Long> views() {
        return Optional.ofNullable(this.views);
    }

    /**
     * Total count of unique video viewers for particular video content.
     */
    public Optional<Long> uniqueViews() {
        return Optional.ofNullable(this.uniqueViews);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Title of the video
     */
    public ViewsByTopContentDetails withVideoTitle(@Nullable String videoTitle) {
        this.videoTitle = videoTitle;
        return this;
    }


    /**
     * Total count of view sessions for a particular video content.
     */
    public ViewsByTopContentDetails withViews(@Nullable Long views) {
        this.views = views;
        return this;
    }


    /**
     * Total count of unique video viewers for particular video content.
     */
    public ViewsByTopContentDetails withUniqueViews(@Nullable Long uniqueViews) {
        this.uniqueViews = uniqueViews;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ViewsByTopContentDetails other = (ViewsByTopContentDetails) o;
        return 
            Utils.enhancedDeepEquals(this.videoTitle, other.videoTitle) &&
            Utils.enhancedDeepEquals(this.views, other.views) &&
            Utils.enhancedDeepEquals(this.uniqueViews, other.uniqueViews);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            videoTitle, views, uniqueViews);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ViewsByTopContentDetails.class,
                "videoTitle", videoTitle,
                "views", views,
                "uniqueViews", uniqueViews);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String videoTitle;

        private Long views;

        private Long uniqueViews;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Title of the video
         */
        public Builder videoTitle(@Nullable String videoTitle) {
            this.videoTitle = videoTitle;
            return this;
        }

        /**
         * Total count of view sessions for a particular video content.
         */
        public Builder views(@Nullable Long views) {
            this.views = views;
            return this;
        }

        /**
         * Total count of unique video viewers for particular video content.
         */
        public Builder uniqueViews(@Nullable Long uniqueViews) {
            this.uniqueViews = uniqueViews;
            return this;
        }

        public ViewsByTopContentDetails build() {
            return new ViewsByTopContentDetails(
                videoTitle, views, uniqueViews);
        }

    }
}
