/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.utils;

/**
 * Implemented by classes that have security annotations on fields.
 **/
public interface HasSecurity {
}