/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.utils;

import java.lang.reflect.Field;

class HeaderMetadata {

    String style = "simple";
    boolean explode;
    String name;

    private HeaderMetadata() {
    }

    // headerParam:style=simple,explode=false,name=apiID
    static HeaderMetadata parse(Field field) throws IllegalArgumentException, IllegalAccessException {
        return Metadata.parse("header", new HeaderMetadata(), field);
    }
}
