/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.utils;

import java.lang.reflect.Field;

class MultipartFormMetadata {

    boolean file;
    boolean content;
    boolean json;
    String name;

    private MultipartFormMetadata() {
    }

    // multipartForm:name=file
    static MultipartFormMetadata parse(Field field) throws IllegalArgumentException, IllegalAccessException {
        return Metadata.parse("multipartForm", new MultipartFormMetadata(), field);
    }
}
