/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
package org.openapis.openapi.utils;

import java.lang.reflect.Field;

class RequestMetadata {

    String mediaType = "application/octet-stream";

    private RequestMetadata() {
    }

    // request:mediaType=multipart/form-data
    static RequestMetadata parse(Field field) throws IllegalArgumentException, IllegalAccessException {
        return Metadata.parse("request", new RequestMetadata(), field);
    }
}
